// Copyright 2025 Open2b. All rights reserved.
// Use of this source code is governed by the MIT license
// that can be found in the LICENSE file.

package postgresql

import (
	"context"
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/meergo/meergo/warehouses"
)

// CanInitialize checks whether the data warehouse can be initialized.
func (warehouse *PostgreSQL) CanInitialize(ctx context.Context) error {
	pool, err := warehouse.connectionPool(ctx)
	if err != nil {
		return err
	}
	const query = `SELECT
		CASE
			"c"."relkind"
			WHEN 'r' THEN 'table'
			WHEN 'm' THEN 'materialized view'
			WHEN 'i' THEN 'index'
			WHEN 'S' THEN 'sequence'
			WHEN 'v' THEN 'view'
			WHEN 'c' THEN 'type'
			ELSE "c"."relkind"::text
		END
	FROM
		"pg_class" "c"
		JOIN "pg_namespace" "n" ON "n"."oid" = "c"."relnamespace"
	WHERE
		"n"."nspname" = $1
		AND "n"."nspname" NOT LIKE 'pg\_toast%'
	ORDER BY
		"c"."relname"`
	rows, err := pool.Query(ctx, query, warehouse.settings.Schema)
	if err != nil {
		return err
	}
	defer rows.Close()
	count := map[string]int{}
	for rows.Next() {
		var typ string
		err := rows.Scan(&typ)
		if err != nil {
			return err
		}
		count[typ] = count[typ] + 1
	}
	if err := rows.Err(); err != nil {
		return err
	}
	// Populate 'errors' to return an error like: «database is not empty (it
	// contains 1 view, 3 sequences, 4 indexes, 5 tables)».
	var errors []string
	for typ, count := range count {
		if count == 1 {
			errors = append(errors, "1 "+typ)
			continue
		}
		if typ == "index" {
			typ += "es"
		} else {
			typ += "s"
		}
		errors = append(errors, strconv.Itoa(count)+" "+typ)
	}
	if errors != nil {
		slices.Sort(errors)
		err := fmt.Errorf("database is not empty (it contains %s)", strings.Join(errors, ", "))
		return warehouses.NewNonInitializableError(err)
	}
	return nil
}

// Initialize initializes the database objects on the data warehouse in order to
// make it work with Meergo.
func (warehouse *PostgreSQL) Initialize(ctx context.Context, profileColumns []warehouses.Column) error {
	return warehouse.initRepairDatabaseObjects(ctx, profileColumns, false)
}

// Repair repairs the database objects on the data warehouse needed by Meergo.
func (warehouse *PostgreSQL) Repair(ctx context.Context, profileColumns []warehouses.Column) error {
	return warehouse.initRepairDatabaseObjects(ctx, profileColumns, true)
}

// initRepairDatabaseObjects initializes (or repairs) the database objects (as
// tables, types, etc...) on the data warehouse.
func (warehouse *PostgreSQL) initRepairDatabaseObjects(ctx context.Context, profileColumns []warehouses.Column, repair bool) error {
	pool, err := warehouse.connectionPool(ctx)
	if err != nil {
		return err
	}
	queries := []string{
		createDestinationProfilesTable,
		createEventsTable,
		createSystemOperationsTable,
		createProfileSchemaVersionsTable,
		identitiesSQLSchema(profileColumns),
		identitiesIndex(),
		profilesSQLSchema("meergo_profiles_0", profileColumns),
	}
	if !repair {
		// Since the "CREATE VIEW IF NOT EXISTS" statement does not exist in
		// PostgreSQL, the view is recreated only if initializing, not when
		// repairing, otherwise a "cannot drop columns from view" error is
		// returned by PostgreSQL in cases where the profiles table has
		// different columns than the default one.
		//
		// TODO(Gianluca): clarify this.
		queries = append(queries, profilesViewSQLSchema(profileColumns, "meergo_profiles_0"))
	}
	for _, query := range queries {
		_, err := pool.Exec(ctx, query)
		if err != nil {
			return err
		}
	}
	return nil
}

// identitiesIndex returns a query in the format "CREATE INDEX ..." that creates
// the necessary indexes for the identities table.
func identitiesIndex() string {
	return `CREATE INDEX IF NOT EXISTS "last_change_time_idx" ON "meergo_identities" ("_updated_at");`
}

// identitiesSQLSchema returns the SQL schema (in the form "CREATE TABLE ...")
// of the identities table, which includes, in addition to the columns used
// internally by the driver, the given profile columns.
func identitiesSQLSchema(profileColumns []warehouses.Column) string {
	var b strings.Builder
	b.WriteString(`CREATE TABLE IF NOT EXISTS meergo_identities (
		"_pk" integer GENERATED BY DEFAULT AS IDENTITY,
		"_pipeline" integer NOT NULL,
		"_is_anonymous" boolean NOT NULL DEFAULT FALSE,
		"_identity_id" text NOT NULL,
		"_connection" integer NOT NULL,
		"_anonymous_ids" text [],
		"_updated_at" timestamp without time zone NOT NULL,
		"_run" integer,
		"_mpid" uuid,
		"_cluster" integer GENERATED BY DEFAULT AS IDENTITY`)
	for _, c := range profileColumns {
		b.WriteString(",\n")
		b.WriteString(quoteIdent(c.Name))
		b.WriteByte(' ')
		b.WriteString(typeToPostgresType(c.Type))
	}
	b.WriteString(",\n" + `PRIMARY KEY ("_pk"))`)
	return b.String()
}

// profilesSQLSchema returns the SQL schema (in the form "CREATE TABLE ...") of
// the profiles table with the given name, which includes, in addition to the
// columns used internally by the driver, the given profile columns.
func profilesSQLSchema(name string, profileColumns []warehouses.Column) string {
	var b strings.Builder
	b.WriteString(`CREATE TABLE IF NOT EXISTS `)
	b.WriteString(quoteIdent(name))
	b.WriteString(` (
		"_mpid" uuid,
		"_identities" int [],
		"_updated_at" timestamp without time zone NOT NULL`)
	for _, c := range profileColumns {
		b.WriteString(",\n")
		b.WriteString(quoteIdent(c.Name))
		b.WriteByte(' ')
		b.WriteString(typeToPostgresType(c.Type))
	}
	b.WriteByte(')')
	return b.String()
}

// profilesViewSQLSchema returns the SQL schema (in the form "CREATE ... VIEW
// ...") of the profiles view which is based on the profiles table with the
// given name.
func profilesViewSQLSchema(profileColumns []warehouses.Column, fromProfilesTable string) string {
	var b strings.Builder
	b.WriteString(`CREATE OR REPLACE VIEW "profiles" AS
		SELECT
			"_mpid",
			"_updated_at"`)
	for _, c := range profileColumns {
		b.WriteString(",\n")
		b.WriteString(quoteIdent(c.Name))
	}
	b.WriteString(` FROM `)
	b.WriteString(quoteIdent(fromProfilesTable))
	return b.String()
}
