encryptionKey: # Key for encryption (ensure it's securely stored)
terminationDelay: 1s # Delay before terminating the server or process

http:
    host: 127.0.0.1 # Server address
    port: 9090 # Port on which the server will listen
    tls:
        enabled: true # Whether TLS (HTTPS) is enabled
        certFile: /path/to/your/certificate.crt # Path to the TLS certificate
        keyFile: /path/to/your/private.key # Path to the TLS private key
    externalURL: https://127.0.0.1:9090/ # External URL exposed to the outside world

db:
    host: 127.0.0.1 # PostgreSQL host address
    port: 5432 # PostgreSQL port
    username: # PostgreSQL username
    password: # PostgreSQL password
    database: # PostgreSQL database
    schema: # PostgreSQL schema

smtp:
    host: # SMTP server host
    port: # SMTP server port
    user: # SMTP username
    pass: # SMTP password

transformations:
    lambda: # AWS Lambda
        accessKeyID: # AWS Lambda access key ID
        secretAccessKey: # AWS Lambda secret access key
        region: # AWS region for Lambda
        role: # AWS Lambda role ARN
        node:
            runtime: nodejs22.x # Node.js runtime version for Lambda
            layer: # Optional Lambda layer for Node.js
        python:
            runtime: python3.13 # Python runtime version for Lambda
            layer: # Optional Lambda layer for Python
    local: # Local execution
        nodeExecutable: /usr/bin/node # Path to the Node.js executable
        pythonExecutable: /usr/bin/python # Path to the Python executable
        functionsDir: ./functions # Directory for local function source files

oauth:
    HubSpot:
        clientID: # OAuth client ID for HubSpot
        clientSecret: # OAuth client secret for HubSpot
    Mailchimp:
        clientID: # OAuth client ID for Mailchimp
        clientSecret: # OAuth client secret for Mailchimp

telemetry:
    enable: false # Enable telemetry for usage data collection
