main:
    host: 127.0.0.1:9090
    https: true
    terminationDelay: 1s

encryptionKey:

esbuild:
    printWarningsOnStderr: false

postgreSQL:
    host: 127.0.0.1
    port: 5432
    username:
    password:
    database:
    schema:

smtp:
    host:
    port:
    user:
    pass:

functionProvider:

    # Configure just one between "lambda" and "local".

    lambda:
        accessKeyID:
        secretAccessKey:
        region:
        role:
        # Every Node and Python 3 runtime is supported.
        # See the list at https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html.
        node:
            runtime: nodejs18.x
            layer:
        python:
            runtime: python3.11
            layer:

    local:
        # Path to the Node executable, eg. "/usr/bin/node" or simply "node".
        nodeExecutable:
        # Path to the Python executable, eg. "/usr/bin/python" or simply "python".
        pythonExecutable:
        # Path to the local directory which will contain the ".js" Node source
        # files (if language is "node") or the ".py" Python source files (if
        # language is "python") for the transformation functions.
        functionsDir:

telemetry:
    # Set "enable" to "true" to enable telemetry.
    #
    # See the documentation within 'doc/src/developers/telemetry.md' for more
    # details.
    enable: false

connectorsOAuth:
    HubSpot:
        clientID:
        clientSecret:
    Mailchimp:
        clientID:
        clientSecret:
