
[Main]
Host=127.0.0.1:9090
# PrintESBuildWarningsOnStderr, when true, prints ESBuild warnings also on the
# standard error.
PrintESBuildWarningsOnStderr=false

[PostgreSQL]
Host=127.0.0.1
Port=5432
Username=
Password=
Database=
Schema=

[Telemetry]
# Set Enable to "true" to enable telemetry.
# In particular, this enables (1) sending traces and logs to Jaeger and (2)
# sending metrics to Prometheus (in both cases passing through the OpenTelemetry
# Collector).
# See the documentation under the directory "telemetry" of this repository for
# more details.
Enable=false