[Main]
# PrintESBuildWarningsOnStderr, when true, prints ESBuild warnings also on the
# standard error.
PrintESBuildWarningsOnStderr=false

[PostgreSQL]
Host=127.0.0.1
Port=5432
Username=
Password=
Database=

[ClickHouse]
Address=127.0.0.1:9000
Username=default
Password=
Database=