services:
  meergo:
    image: meergo:dev
    ports:
      - 9090:9090
    environment:
      MEERGO_ENCRYPTION_KEY: 6uA9ccQxZ+/1PlqXZFR49QZ0fnQDCNZIugyKwHv3WdkqcoIA3iSwuuj1yvM+f2cZFQ7Saqjq695Y0AP+rlZDOg==
      MEERGO_HTTP_HOST: meergo
      MEERGO_HTTP_PORT: 9090
      MEERGO_HTTP_EXTERNAL_URL: http://127.0.0.1:9090/
      MEERGO_DB_HOST: db
      MEERGO_DB_PORT: 5432
      MEERGO_DB_USERNAME: meergo
      MEERGO_DB_PASSWORD: meergo
      MEERGO_DB_DATABASE: meergo
      MEERGO_TRANSFORMATIONS_LOCAL_NODE_EXECUTABLE: /usr/bin/node
      MEERGO_TRANSFORMATIONS_LOCAL_PYTHON_EXECUTABLE: /usr/bin/python
      MEERGO_TRANSFORMATIONS_LOCAL_FUNCTIONS_DIR: /bin/meergo-files/transformation-functions
      # Telemetry (for collecting errors, crash reports, etc...) is enabled by default.
      # Uncomment the following line to disable it:
      # MEERGO_DISABLE_TELEMETRY="true"
    volumes:
      - ./docker-compose:/bin/meergo-files
    depends_on:
      db:
        condition: service_healthy
      warehouse:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: meergo
      POSTGRES_PASSWORD: meergo
      POSTGRES_DB: meergo
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meergo"]
      interval: 5s
      timeout: 5s
      retries: 5

  warehouse:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - warehouse:/var/lib/postgresql/data

volumes:
  db:
  warehouse:
