# This file is intended to be KEPT AS MINIMAL AS POSSIBLE, as its purpose is to
# test a version as similar as possible to the one executed by 'compose.yaml',
# with the only difference that here Krenalis is compiled directly from the
# repository instead of being retrieved from Docker Hub.

services:
  krenalis:
    image: ""
    build:
      context: .
