# This is the Docker Compose file that runs the latest released image of Meergo.
#
# For customizing the Meergo instance, see https://www.meergo.com/docs/configuration.
#

services:
  meergo:
    image: meergocdp/meergo:v0.21.0
    command: -init-db-if-empty -init-docker-member
    restart: on-failure
    ports:
      - 2022:2022
    environment:
      # For information on how to configure these environment variables and
      # enable additional features, see:
      # https://www.meergo.com/docs/configuration/docker-compose-file.

      # Exposing Meergo externally.
      MEERGO_HTTP_EXTERNAL_URL: http://127.0.0.1:2022/
      MEERGO_METRICS_ENABLED: true

      # Email invitations and password recovery.
      MEERGO_MEMBER_EMAIL_VERIFICATION_REQUIRED: false
      MEERGO_MEMBER_EMAIL_FROM:
      MEERGO_SMTP_HOST:
      MEERGO_SMTP_PORT:
      MEERGO_SMTP_USERNAME:
      MEERGO_SMTP_PASSWORD:

      # Event geolocation enrichment.
      MEERGO_MAXMIND_DB_PATH:

      # Transformations with AWS Lambda.
      MEERGO_TRANSFORMERS_PROVIDER: local
      MEERGO_TRANSFORMERS_AWS_LAMBDA_ACCESS_KEY_ID:
      MEERGO_TRANSFORMERS_AWS_LAMBDA_SECRET_ACCESS_KEY:
      MEERGO_TRANSFORMERS_AWS_LAMBDA_REGION:
      MEERGO_TRANSFORMERS_AWS_LAMBDA_ROLE:
      MEERGO_TRANSFORMERS_AWS_LAMBDA_NODEJS_RUNTIME:
      MEERGO_TRANSFORMERS_AWS_LAMBDA_NODEJS_LAYER:
      MEERGO_TRANSFORMERS_AWS_LAMBDA_PYTHON_RUNTIME:
      MEERGO_TRANSFORMERS_AWS_LAMBDA_PYTHON_LAYER:

      # OAuth for HubSpot.
      MEERGO_OAUTH_HUBSPOT_CLIENT_ID:
      MEERGO_OAUTH_HUBSPOT_CLIENT_SECRET:

      # OAuth for Mailchimp.
      MEERGO_OAUTH_MAILCHIMP_CLIENT_ID:
      MEERGO_OAUTH_MAILCHIMP_CLIENT_SECRET:

      # Telemetry.
      MEERGO_TELEMETRY_LEVEL:

      # DO NOT CHANGE THESE SETTINGS unless you know what you are doing.
      MEERGO_HTTP_HOST: meergo
      MEERGO_DB_HOST: db
      MEERGO_DB_PORT: 5432
      MEERGO_DB_USERNAME: meergo
      MEERGO_DB_PASSWORD: meergo
      MEERGO_DB_DATABASE: meergo
      MEERGO_NATS_URL: nats://nats:4222
      MEERGO_NATS_USER: ruser
      MEERGO_NATS_PASSWORD: T0pS3cr3t
      MEERGO_TRANSFORMERS_LOCAL_NODEJS_EXECUTABLE: /usr/bin/node
      MEERGO_TRANSFORMERS_LOCAL_PYTHON_EXECUTABLE: /usr/bin/python
      MEERGO_TRANSFORMERS_LOCAL_FUNCTIONS_DIR: /var/meergo/transformation-functions
      MEERGO_TRANSFORMERS_LOCAL_DOAS_USER: transformeruser
      MEERGO_CONNECTOR_FILESYSTEM_ROOT: /var/meergo/storage
      MEERGO_CONNECTOR_FILESYSTEM_DISPLAYED_ROOT: ${PWD}/storage

    volumes:
      - ./storage:/var/meergo/storage
      - transformation-functions:/var/meergo/transformation-functions
    depends_on:
      db:
        condition: service_healthy
      warehouse:
        condition: service_healthy

  db:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_USER: meergo
      POSTGRES_PASSWORD: meergo
      POSTGRES_DB: meergo
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meergo"]
      interval: 5s
      timeout: 5s
      retries: 5

  warehouse:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - warehouse:/var/lib/postgresql/data

  nats:
    image: nats:2.12-alpine3.22
    command: --jetstream --store_dir /var/lib/nats/jetstream_storage
    volumes:
      - jetstream_storage:/var/lib/nats/jetstream_storage

volumes:
  db:
  warehouse:
  jetstream_storage:
  transformation-functions:
