# This Docker Compose is intended to run ONLY the INFRASTRUCTURE needed by
# Meergo during development (database, NATS, monitoring, etc.), NOT MEERGO
# ITSELF, which must be compiled and run separately as a process on the host
# system.
#
# Running this Compose, you get:
#
# =============================================================================
# Meergo PostgreSQL database
# -----------------------------------------------------------------------------
#
#     Username:             <your system username>
#     Password:             no password set (auth method = trust)
#     Port:                 22000
#     Database:             meergo
#     Connecting from CLI:  psql -h 127.0.0.1 -p 22000 meergo
#
# =============================================================================
# Meergo PostgreSQL warehouse
# -----------------------------------------------------------------------------
#
#     Username:             <your system username>
#     Password:             no password set (auth method = trust)
#     Port:                 22001
#     Database:             warehouse
#     Connecting from CLI:  psql -h 127.0.0.1 -p 22001 warehouse
#
# =============================================================================
# NATS
# -----------------------------------------------------------------------------
#
#     URL:       nats://localhost:4222
#     User:      ruser
#     Password:  T0pS3cr3t
#
# =============================================================================
# Prometheus
# -----------------------------------------------------------------------------
#
#     Expected Meergo instance at:  http://localhost:2022
#     Exposes metrics at:           http://localhost:9090
#
# =============================================================================
# Grafana
# -----------------------------------------------------------------------------
#
#     Panel:         http://localhost:3000
#     Dashboards:    ./tools/compose/grafana/dashboards
#     Data sources:  ./tools/compose/grafana/provisioning/datasources
#
# =============================================================================
# Recommended env vars for your .env file:
# -----------------------------------------------------------------------------
#
#     MEERGO_DB_DATABASE=meergo
#     MEERGO_DB_PASSWORD=<your system username>
#     MEERGO_DB_USERNAME=<your system username>
#     MEERGO_DB_USERNAME_PORT=20000
#     MEERGO_NATS_URL=nats://localhost:4222
#     MEERGO_NATS_USER=ruser
#     MEERGO_NATS_PASSWORD=T0pS3cr3t

name: meergo-dev

services:
  db:
    image: postgres:18.1-alpine3.23
    restart: always
    ports:
      - "22000:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${USER}
      POSTGRES_DB: meergo
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER} meergo"]
      interval: 5s
      timeout: 5s
      retries: 5

  warehouse:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${USER}
      POSTGRES_DB: warehouse
    ports:
      - "22001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER} warehouse"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - warehouse:/var/lib/postgresql/data

  nats:
    image: nats:2.12-alpine3.22
    command: --jetstream --store_dir /var/lib/nats/jetstream_storage
    volumes:
      - jetstream_storage:/var/lib/nats/jetstream_storage

  prometheus:
    image: prom/prometheus
    volumes:
      - ./tools/compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./tools/compose/grafana/provisioning:/etc/grafana/provisioning
      - ./tools/compose/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./tools/compose/grafana/dashboards:/var/lib/grafana/dashboards
    attach: false # set to 'true' to enable Grafana logging (note: it is very verbose)

volumes:
  db:
  warehouse:
  jetstream_storage:
  transformation-functions:
