//
// SPDX-License-Identifier: Elastic-2.0
//
//
// Copyright (c) 2022 Open2b
//

package state

import (
	"context"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"slices"
	"sort"
	"sync"
	"time"

	"github.com/meergo/meergo"
	"github.com/meergo/meergo/core/db"
	"github.com/meergo/meergo/types"

	"github.com/google/uuid"
)

// election represents a leader election.
type election struct {
	number   int
	leader   uuid.UUID
	lastSeen time.Time
}

// metadata represents the metadata associated with a Meergo instance.
type metadata struct {
	// encryptionKey is a slice of random bytes of length 64.
	encryptionKey []byte

	// installationID is an identifier that uniquely identifies a Meergo
	// installation. It is generated by the PostgreSQL installation script and
	// cannot change over time.
	installationID string
}

// State represents the application state.
type State struct {
	id uuid.UUID
	db *db.DB

	changing       *sync.RWMutex
	connectors     map[string]*Connector
	warehouseTypes map[string]WarehouseType
	metadata       metadata

	mu               *sync.Mutex            // for the 'actions', ..., and 'workspaces' fields
	actions          map[int]*Action        // protected by mu
	connections      map[int]*Connection    // protected by mu
	connectionsByKey map[string]*Connection // protected by mu
	apiKeyByToken    map[string]*APIKey     // protected by mu
	election         election               // protected by mu
	organizations    map[int]*Organization  // protected by mu
	workspaces       map[int]*Workspace     // protected by mu

	notifications struct {
		*notifier
		ch   <-chan notification
		acks sync.Map
	}
	listeners []any
	close     struct {
		ctx    context.Context
		cancel context.CancelFunc
		sync.WaitGroup
	}
}

// ConnectorOAuth represents the OAuth client credentials for a connector.
type ConnectorOAuth struct {
	ClientID     string
	ClientSecret string
}

// New returns a state given the database, and the OAuth client credentials for
// connectors.
func New(db *db.DB, connectorsOAuth map[string]*ConnectorOAuth) (*State, error) {

	id, err := uuid.NewUUID()
	if err != nil {
		return nil, err
	}

	state := &State{
		id:               id,
		db:               db,
		mu:               new(sync.Mutex),
		changing:         new(sync.RWMutex),
		organizations:    map[int]*Organization{},
		connectors:       map[string]*Connector{},
		workspaces:       map[int]*Workspace{},
		connections:      map[int]*Connection{},
		connectionsByKey: map[string]*Connection{},
		actions:          map[int]*Action{},
	}

	// Init the notifier.
	ch := make(chan notification, 10)
	state.notifications.notifier = newNotifier(db, ch)
	state.notifications.ch = ch

	state.close.ctx, state.close.cancel = context.WithCancel(context.Background())

	// Load the state.
	err = state.load(connectorsOAuth)
	if err != nil {
		state.notifications.Close()
		return nil, err
	}

	// Keep the state updated.
	state.close.Add(1)
	go state.keep()

	// Keep elections.
	state.close.Add(1)
	go state.keepElections()

	return state, nil
}

// APIKeyByToken returns the API key with the provided token.
// The boolean return value reports whether the API key exists.
func (state *State) APIKeyByToken(token string) (*APIKey, bool) {
	state.mu.Lock()
	key, ok := state.apiKeyByToken[token]
	state.mu.Unlock()
	return key, ok
}

// Account returns the account with identifier id.
// The boolean return value reports whether the account exists.
func (state *State) Account(id int) (*Account, bool) {
	for _, ws := range state.Workspaces() {
		if a, ok := ws.Account(id); ok {
			return a, true
		}
	}
	return nil, false
}

// Action returns the action with identifier id.
// The boolean return value reports whether the action exists.
func (state *State) Action(id int) (*Action, bool) {
	state.mu.Lock()
	a, ok := state.actions[id]
	state.mu.Unlock()
	return a, ok
}

// Actions returns all the actions from every connection.
func (state *State) Actions() []*Action {
	state.mu.Lock()
	actions := make([]*Action, len(state.actions))
	i := 0
	for _, action := range state.actions {
		actions[i] = action
		i++
	}
	state.mu.Unlock()
	sort.Slice(actions, func(i, j int) bool {
		return actions[i].ID < actions[j].ID
	})
	return actions
}

// Close closes the state. When it is called, no calls to the State methods
// should be in progress, and no further calls should be made.
func (state *State) Close() {
	state.close.cancel()
	state.close.Wait()
	state.notifications.Close()
}

// Connection returns the connection with identifier id.
// The boolean return value reports whether the connection exists.
func (state *State) Connection(id int) (*Connection, bool) {
	state.mu.Lock()
	c, ok := state.connections[id]
	state.mu.Unlock()
	return c, ok
}

// ConnectionByKey returns the connection with the given key.
// The boolean return value reports whether the key exists.
func (state *State) ConnectionByKey(key string) (*Connection, bool) {
	state.mu.Lock()
	c, ok := state.connectionsByKey[key]
	state.mu.Unlock()
	return c, ok
}

// Connections returns all connections.
func (state *State) Connections() []*Connection {
	i := 0
	state.mu.Lock()
	connections := make([]*Connection, len(state.connections))
	for _, c := range state.connections {
		connections[i] = c
		i++
	}
	state.mu.Unlock()
	return connections
}

// Connector returns the connector with the provided name.
// The boolean return value reports whether the connector exists.
func (state *State) Connector(name string) (*Connector, bool) {
	state.mu.Lock()
	c, ok := state.connectors[name]
	state.mu.Unlock()
	return c, ok
}

// Connectors returns all connectors.
func (state *State) Connectors() []*Connector {
	state.mu.Lock()
	connectors := make([]*Connector, len(state.connectors))
	i := 0
	for _, connector := range state.connectors {
		connectors[i] = connector
		i++
	}
	state.mu.Unlock()
	sort.Slice(connectors, func(i, j int) bool {
		return connectors[i].Name < connectors[j].Name
	})
	return connectors
}

// EncryptionKey returns the encryption key. It is 64 bytes long.
func (state *State) EncryptionKey() []byte {
	return state.metadata.encryptionKey
}

// Freeze freezes the state. If the state is updating, the calling goroutine
// blocks until the update and the corresponding calls to the listeners are
// completed. When the state is frozen, no changes are made to the state. For
// each call to Freeze, a call to Unfreeze must be made to unfreeze the state.
func (state *State) Freeze() {
	state.changing.RLock()
}

// ID returns the node identifier.
func (state *State) ID() uuid.UUID {
	return state.id
}

// InstallationID returns the installation ID.
func (state *State) InstallationID() string {
	return state.metadata.installationID
}

// IsLeader reports whether this node is the leader.
func (state *State) IsLeader() bool {
	state.mu.Lock()
	election := state.election
	state.mu.Unlock()
	return election.leader == state.id
}

// Organization returns the organization with identifier id.
// The boolean return value reports whether the organization exists.
func (state *State) Organization(id int) (*Organization, bool) {
	state.mu.Lock()
	a, ok := state.organizations[id]
	state.mu.Unlock()
	return a, ok
}

// Organizations returns all organizations.
func (state *State) Organizations() []*Organization {
	state.mu.Lock()
	organizations := make([]*Organization, len(state.organizations))
	i := 0
	for _, organization := range state.organizations {
		organizations[i] = organization
		i++
	}
	state.mu.Unlock()
	sort.Slice(organizations, func(i, j int) bool {
		return organizations[i].ID < organizations[j].ID
	})
	return organizations
}

// Transaction executes f in a transaction.
func (state *State) Transaction(ctx context.Context, f func(tx *db.Tx) (any, error)) error {
	tx, err := state.db.Begin(ctx)
	if err != nil {
		return err
	}
	var id int64
	var ack chan struct{}
	defer func() {
		if err := recover(); err != nil {
			_ = tx.Rollback(ctx)
			panic(err)
		}
	}()
	n, err := f(tx)
	if err != nil {
		_ = tx.Rollback(ctx)
		return err
	}
	if n == nil {
		return tx.Commit(ctx)
	}
	id, err = state.notifications.Notify(ctx, tx, n)
	if err != nil {
		_ = tx.Rollback(ctx)
		return err
	}
	if id == 0 {
		return tx.Commit(ctx)
	}
	ack = make(chan struct{})
	state.notifications.acks.Store(id, ack)
	defer func() {
		if ack == nil {
			return
		}
		// Attempt to delete the ack channel.
		if _, ok := state.notifications.acks.LoadAndDelete(id); !ok {
			// If the keeper has already removed it, the notification was received.
			// To prevent blocking the keeper, receive from the channel.
			<-ack
		}
	}()
	err = tx.Commit(ctx)
	if err != nil {
		return err
	}
	<-ack
	ack = nil
	return nil
}

// Unfreeze unfreezes the state if there are no more pending Unfreeze calls.
func (state *State) Unfreeze() {
	state.changing.RUnlock()
}

// WarehouseType returns the warehouse type with the provided name.
// The boolean return value reports whether the warehouse type exists.
func (state *State) WarehouseType(name string) (WarehouseType, bool) {
	state.mu.Lock()
	wh, ok := state.warehouseTypes[name]
	state.mu.Unlock()
	return wh, ok
}

// WarehouseTypes returns all warehouse types.
func (state *State) WarehouseTypes() []WarehouseType {
	state.mu.Lock()
	types := make([]WarehouseType, len(state.warehouseTypes))
	i := 0
	for _, t := range state.warehouseTypes {
		types[i] = t
		i++
	}
	state.mu.Unlock()
	sort.Slice(types, func(i, j int) bool {
		return types[i].Name < types[j].Name
	})
	return types
}

// Workspace returns the workspace with identifier id.
// The boolean return value reports whether the workspace exists.
func (state *State) Workspace(id int) (*Workspace, bool) {
	state.mu.Lock()
	ws, ok := state.workspaces[id]
	state.mu.Unlock()
	return ws, ok
}

// Workspaces returns all the workspaces.
func (state *State) Workspaces() []*Workspace {
	i := 0
	state.mu.Lock()
	workspaces := make([]*Workspace, len(state.workspaces))
	for _, ws := range state.workspaces {
		workspaces[i] = ws
		i++
	}
	state.mu.Unlock()
	return workspaces
}

// APIKey represents an API key.
type APIKey struct {
	ID           int
	Organization int
	Workspace    int
}

// Organization represents an organization.
type Organization struct {
	mu         *sync.Mutex
	workspaces map[int]*Workspace
	ID         int
	Name       string
}

// Workspace returns the workspace of the organization with identifier id.
// The boolean return value reports whether the workspace exists.
func (organization *Organization) Workspace(id int) (*Workspace, bool) {
	organization.mu.Lock()
	w, ok := organization.workspaces[id]
	organization.mu.Unlock()
	return w, ok
}

// Workspaces returns all the workspaces of the organization.
func (organization *Organization) Workspaces() []*Workspace {
	organization.mu.Lock()
	workspaces := make([]*Workspace, len(organization.workspaces))
	i := 0
	for _, w := range organization.workspaces {
		workspaces[i] = w
		i++
	}
	organization.mu.Unlock()
	return workspaces
}

// WarehouseType represents a warehouse type.
type WarehouseType struct {
	Name string
	Icon string
}

// WarehouseMode represents a data warehouse mode.
type WarehouseMode int

const (
	Normal WarehouseMode = iota
	Inspection
	Maintenance
)

// Scan implements the sql.Scanner interface.
func (mode *WarehouseMode) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an WarehouseMode value", src)
	}
	var m WarehouseMode
	switch s {
	case "Normal":
		m = Normal
	case "Inspection":
		m = Inspection
	case "Maintenance":
		m = Maintenance
	default:
		return fmt.Errorf("invalid WarehouseMode: %s", s)
	}
	*mode = m
	return nil
}

// String returns the string representation of mode.
// It panics if mode is not a valid WarehouseMode value.
func (mode WarehouseMode) String() string {
	m, err := mode.Value()
	if err != nil {
		panic("invalid warehouse mode")
	}
	return m.(string)
}

// Value implements driver.Valuer interface.
// It returns an error if typ is not a valid WarehouseMode.
func (mode WarehouseMode) Value() (driver.Value, error) {
	switch mode {
	case Normal:
		return "Normal", nil
	case Inspection:
		return "Inspection", nil
	case Maintenance:
		return "Maintenance", nil
	}
	return nil, fmt.Errorf("not a valid WarehouseMode: %d", mode)
}

// Workspace represents a workspace.
type Workspace struct {
	mu        *sync.Mutex
	Warehouse struct {
		Type     string
		Mode     WarehouseMode
		Settings json.RawMessage
	}
	connections                    map[int]*Connection
	executions                     map[int]*ActionExecution // running action executions.
	ID                             int
	organization                   *Organization
	Name                           string
	UserSchema                     types.Type // without meta properties.
	UserPrimarySources             map[string]int
	accounts                       map[int]*Account
	ResolveIdentitiesOnBatchImport bool
	Identifiers                    []string
	UIPreferences                  UIPreferences
	IR                             struct {
		ID        *string    // nil means no IR in execution.
		StartTime *time.Time // nil means IR was never started.
		EndTime   *time.Time // nil means IR is running or has never started.
	}
	AlterUserSchema struct {
		ID             *string    // nil means no user schema alterations in execution.
		StartTime      *time.Time // nil means user schema alteration was never started.
		EndTime        *time.Time // nil means user schema alteration is running or has never started.
		Err            *string    // pointer to empty string if no errors occurred during last execution of alter user schema.
		Schema         types.Type
		PrimarySources map[string]int // nil if, and only if, schema alteration is not in execution.
		Operations     []meergo.AlterOperation
	}
	actionsToPurge []int
}

// Account returns the account with identifier id. The boolean return value
// reports whether the account exists.
func (workspace *Workspace) Account(id int) (*Account, bool) {
	workspace.mu.Lock()
	a, ok := workspace.accounts[id]
	workspace.mu.Unlock()
	return a, ok
}

// AccountByCode returns the account with the given code for the specified
// connector. The boolean indicates whether the account exists.
func (workspace *Workspace) AccountByCode(connector, code string) (*Account, bool) {
	var a *Account
	workspace.mu.Lock()
	for _, account := range workspace.accounts {
		if account.connector.Name == connector && account.Code == code {
			a = account
			break
		}
	}
	workspace.mu.Unlock()
	return a, a != nil
}

// ActionsToPurge returns the identifiers of actions that require purging,
// specifically those that have been deleted but still have user identifiers to
// be purged from the data warehouse. Returns nil if the data warehouse is not
// connected.
func (workspace *Workspace) ActionsToPurge() []int {
	workspace.mu.Lock()
	actions := workspace.actionsToPurge
	workspace.mu.Unlock()
	return slices.Clone(actions)
}

// Connection returns the connection of the workspace with identifier id.
// The boolean return value reports whether the connection exists.
func (workspace *Workspace) Connection(id int) (*Connection, bool) {
	workspace.mu.Lock()
	c, ok := workspace.connections[id]
	workspace.mu.Unlock()
	return c, ok
}

// Connections returns all the connections of the workspace.
func (workspace *Workspace) Connections() []*Connection {
	workspace.mu.Lock()
	connections := make([]*Connection, len(workspace.connections))
	i := 0
	for _, c := range workspace.connections {
		connections[i] = c
		i++
	}
	workspace.mu.Unlock()
	return connections
}

// Execution returns the action execution of the workspace with the given id.
// The boolean return value reports whether the execution exists.
func (workspace *Workspace) Execution(id int) (*ActionExecution, bool) {
	workspace.mu.Lock()
	exe, ok := workspace.executions[id]
	workspace.mu.Unlock()
	return exe, ok
}

// NumActionsToPurge returns the number of actions to purge for the workspace.
func (workspace *Workspace) NumActionsToPurge() int {
	workspace.mu.Lock()
	n := len(workspace.actionsToPurge)
	workspace.mu.Unlock()
	return n
}

// Organization returns the organization of the workspace.
func (workspace *Workspace) Organization() *Organization {
	workspace.mu.Lock()
	organization := workspace.organization
	workspace.mu.Unlock()
	return organization
}

// UIPreferences represents the UI preferences of a workspace.
type UIPreferences struct {
	UserProfile struct {
		Image     string // property path.
		FirstName string // property path.
		LastName  string // property path.
		Extra     string // property path.
	}
}

// TimeLayouts represents the layouts used to format datetime, date, and time
// values.
type TimeLayouts struct {
	DateTime string
	Date     string
	Time     string
}

// Connector represents a connector.
type Connector struct {
	Name                   string
	Icon                   string
	Type                   ConnectorType
	Categories             meergo.Category
	SourceTargets          ConnectorTargets
	DestinationTargets     ConnectorTargets
	Terms                  ConnectorTerms
	SendingMode            *SendingMode
	HasSheets              bool
	HasSourceSettings      bool
	HasDestinationSettings bool
	IdentityIDLabel        string
	TimeLayouts            TimeLayouts
	FileExtension          string
	SampleQuery            string
	WebhooksPer            WebhooksPer
	OAuth                  *OAuth
	BackoffPolicy          meergo.BackoffPolicy
	Strategies             bool
	Documentation          meergo.ConnectorDocumentation
}

// ConnectorTargets represents the targets of a connector.
type ConnectorTargets int

const (
	EventsFlag ConnectorTargets = 1 << iota
	UsersFlag
	GroupsFlag
)

// Contains reports whether t contains the given target.
func (t ConnectorTargets) Contains(target Target) bool {
	switch target {
	case Events:
		return t&EventsFlag != 0
	case Users:
		return t&UsersFlag != 0
	case Groups:
		return t&GroupsFlag != 0
	}
	panic("invalid target")
}

// ConnectorTerms represents the terms that a connector uses to refer to various
// entities, such as users or groups.
type ConnectorTerms struct {
	User  string
	Users string
	// Group  string  TODO(Marco): implement groups
	// Groups string
}

// ConnectorType represents a connector type.
type ConnectorType int

const (
	App ConnectorType = iota + 1
	Database
	File
	FileStorage
	SDK
	Stream
)

// Scan implements the sql.Scanner interface.
func (typ *ConnectorType) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.ConnectorType value", src)
	}
	var t ConnectorType
	switch s {
	case "App":
		t = App
	case "Database":
		t = Database
	case "File":
		t = File
	case "FileStorage":
		t = FileStorage
	case "SDK":
		t = SDK
	case "Stream":
		t = Stream
	default:
		return fmt.Errorf("invalid state.ConnectionType: %s", s)
	}
	*typ = t
	return nil
}

// String returns the string representation of typ.
// It panics if typ is not a valid ConnectorType value.
func (typ ConnectorType) String() string {
	s, err := typ.Value()
	if err != nil {
		panic("invalid connector type")
	}
	return s.(string)
}

// Value implements driver.Valuer interface.
// It returns an error if typ is not a valid ConnectorType.
func (typ ConnectorType) Value() (driver.Value, error) {
	switch typ {
	case App:
		return "App", nil
	case Database:
		return "Database", nil
	case File:
		return "File", nil
	case FileStorage:
		return "FileStorage", nil
	case SDK:
		return "SDK", nil
	case Stream:
		return "Stream", nil
	}
	return nil, fmt.Errorf("not a valid ConnectorType: %d", typ)
}

type WebhooksPer int

const (
	WebhooksPerNone WebhooksPer = iota
	WebhooksPerAccount
	WebhooksPerConnection
	WebhooksPerConnector
)

// Scan implements the sql.Scanner interface.
func (per *WebhooksPer) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.WebhooksPer value", src)
	}
	var p WebhooksPer
	switch s {
	case "None":
		p = WebhooksPerNone
	case "Account":
		p = WebhooksPerAccount
	case "Connection":
		p = WebhooksPerConnection
	case "Connector":
		p = WebhooksPerConnector
	default:
		return fmt.Errorf("invalid state.WebhooksPer: %s", s)
	}
	*per = p
	return nil
}

// String returns the string representation of w.
// It panics if w is not a valid WebhooksPer value.
func (per WebhooksPer) String() string {
	s, err := per.Value()
	if err != nil {
		panic("invalid webhooksPer value")
	}
	return s.(string)
}

// Value implements driver.Valuer interface.
// It returns an error if typ is not a valid Role.
func (per WebhooksPer) Value() (driver.Value, error) {
	switch per {
	case WebhooksPerNone:
		return "None", nil
	case WebhooksPerAccount:
		return "Account", nil
	case WebhooksPerConnection:
		return "Connection", nil
	case WebhooksPerConnector:
		return "Connector", nil
	}
	return nil, fmt.Errorf("not a valid WebhooksPer: %d", per)
}

// An OAuth represents OAuth data required to authenticate with a connector.
type OAuth struct {
	meergo.OAuth
	ClientID     string
	ClientSecret string
}

// Account represents an account.
type Account struct {
	mu           *sync.Mutex
	ID           int
	workspace    *Workspace
	connector    *Connector
	Code         string
	AccessToken  string
	RefreshToken string
	ExpiresIn    time.Time
}

// Workspace returns the workspace of the account.
func (account *Account) Workspace() *Workspace {
	account.mu.Lock()
	w := account.workspace
	account.mu.Unlock()
	return w
}

// Connector returns the connector of the account.
func (account *Account) Connector() *Connector {
	account.mu.Lock()
	c := account.connector
	account.mu.Unlock()
	return c
}

// Strategy represents a strategy.
// Can be "Conversion", "Fusion", "Isolation", and "Preservation".
type Strategy string

// Connection represents a connection.
type Connection struct {
	mu                *sync.Mutex
	organization      *Organization
	workspace         *Workspace
	ID                int
	Name              string
	connector         *Connector
	Role              Role
	account           *Account
	Strategy          *Strategy
	SendingMode       *SendingMode
	LinkedConnections []int // It’s nil if events aren’t supported or if there are no linked connections.
	Keys              []string
	Settings          []byte
	UsersQuery        string
	actions           map[int]*Action
	Health            Health
}

// Action returns the action of the connection with identifier id.
// The boolean return value reports whether the action exists.
func (connection *Connection) Action(id int) (*Action, bool) {
	connection.mu.Lock()
	a, ok := connection.actions[id]
	connection.mu.Unlock()
	return a, ok
}

// Actions returns the actions of the connection.
func (connection *Connection) Actions() []*Action {
	connection.mu.Lock()
	actions := make([]*Action, len(connection.actions))
	i := 0
	for _, a := range connection.actions {
		actions[i] = a
		i++
	}
	connection.mu.Unlock()
	sort.Slice(actions, func(i, j int) bool {
		return actions[i].ID < actions[j].ID
	})
	return actions
}

// Connector returns the connector of the connection.
func (connection *Connection) Connector() *Connector {
	connection.mu.Lock()
	c := connection.connector
	connection.mu.Unlock()
	return c
}

// Organization returns the organization of the connection.
func (connection *Connection) Organization() *Organization {
	connection.mu.Lock()
	o := connection.organization
	connection.mu.Unlock()
	return o
}

// Account returns the account of the connection. The boolean return value
// reports whether the connection has an account.
func (connection *Connection) Account() (*Account, bool) {
	connection.mu.Lock()
	a := connection.account
	connection.mu.Unlock()
	return a, a != nil
}

// Workspace returns the workspace of the connection.
func (connection *Connection) Workspace() *Workspace {
	connection.mu.Lock()
	w := connection.workspace
	connection.mu.Unlock()
	return w
}

// Health is an indicator of the current state of an action or a connection.
type Health int

const (
	Healthy Health = iota
	NoRecentData
	RecentError
)

// Scan implements the sql.Scanner interface.
func (health *Health) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Health value", src)
	}
	var h Health
	switch s {
	case "Healthy":
		h = Healthy
	case "NoRecentData":
		h = NoRecentData
	case "RecentError":
		h = RecentError
	default:
		return fmt.Errorf("invalid state.Health: %s", s)
	}
	*health = h
	return nil
}

// String returns the string representation of health.
// It panics if health is not a valid Health value.
func (health Health) String() string {
	switch health {
	case Healthy:
		return "Healthy"
	case NoRecentData:
		return "NoRecentData"
	case RecentError:
		return "RecentError"
	}
	panic("invalid connection health")
}

// Value implements driver.Valuer interface.
// It returns an error if health is not a valid Health.
func (health Health) Value() (driver.Value, error) {
	switch health {
	case Healthy:
		return "Healthy", nil
	case NoRecentData:
		return "NoRecentData", nil
	case RecentError:
		return "RecentError", nil
	}
	return nil, fmt.Errorf("not a valid Health: %d", health)
}

// Role represents a role.
type Role int

const (
	Both        Role = iota // both
	Source                  // source
	Destination             // destination
)

// Scan implements the sql.Scanner interface.
func (role *Role) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Role value", src)
	}
	var r Role
	switch s {
	case "Both":
		r = Both
	case "Source":
		r = Source
	case "Destination":
		r = Destination
	default:
		return fmt.Errorf("invalid state.Role: %s", s)
	}
	*role = r
	return nil
}

// String returns the string representation of role.
// It panics if role is not a valid Role value.
func (role Role) String() string {
	switch role {
	case Source:
		return "Source"
	case Destination:
		return "Destination"
	}
	panic("invalid connection role")
}

// Value implements driver.Valuer interface.
// It returns an error if role is not a valid Role.
func (role Role) Value() (driver.Value, error) {
	switch role {
	case Source:
		return "Source", nil
	case Destination:
		return "Destination", nil
	}
	return nil, fmt.Errorf("not a valid Role: %d", role)
}

// SendingMode represents a sending mode.
type SendingMode string

const (
	Cloud    SendingMode = "Cloud"
	Device   SendingMode = "Device"
	Combined SendingMode = "Combined"
)

func (sm SendingMode) Contains(mode SendingMode) bool {
	return sm == Combined || sm == mode
}

// Compression represents the compression of a file connection.
type Compression string

const (
	NoCompression     Compression = ""
	ZipCompression    Compression = "Zip"
	GzipCompression   Compression = "Gzip"
	SnappyCompression Compression = "Snappy"
)

// ContentType returns the content type to use for a file compressed with
// compression c. It returns an empty string if c is NoCompression.
func (c Compression) ContentType() string {
	switch c {
	case NoCompression:
		return ""
	case ZipCompression:
		return "application/zip"
	case GzipCompression:
		return "application/gzip"
	case SnappyCompression:
		return "application/x-snappy-framed"
	}
	panic(fmt.Sprintf("invalid state.Compression: %s", c))
}

// Ext returns the file extension to use when the file is compressed with
// compression c. It returns an empty string if c is NoCompression.
func (c Compression) Ext() string {
	switch c {
	case NoCompression:
		return ""
	case ZipCompression:
		return ".zip"
	case GzipCompression:
		return ".gz"
	case SnappyCompression:
		return ".sz"
	}
	panic(fmt.Sprintf("invalid state.Compression: %s", c))
}

// Target represents a target.
type Target int

const (
	Events Target = iota + 1
	Users
	Groups
)

// Scan implements the sql.Scanner interface.
func (target *Target) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Target value", src)
	}
	switch s {
	case "Events":
		*target = Events
	case "Users":
		*target = Users
	case "Groups":
		*target = Groups
	default:
		return fmt.Errorf("invalid state.Target: %s", s)
	}
	return nil
}

// String returns the string representation of target.
// It panics if target is not a valid Target value.
func (target Target) String() string {
	switch target {
	case Events:
		return "Events"
	case Users:
		return "Users"
	case Groups:
		return "Groups"
	}
	panic("invalid target")
}

// Value implements driver.Valuer interface.
// It returns an error if target is not a valid Target.
func (target Target) Value() (driver.Value, error) {
	switch target {
	case Events:
		return "Events", nil
	case Users:
		return "Users", nil
	case Groups:
		return "Groups", nil
	}
	return nil, fmt.Errorf("not a valid Target: %d", target)
}

type Action struct {
	mu                   *sync.Mutex
	ID                   int
	connection           *Connection
	format               *Connector
	execution            *ActionExecution
	propertiesToUnset    []string // is not nil only for source actions on users.
	Target               Target
	Name                 string
	Enabled              bool
	EventType            string
	ScheduleStart        int16
	SchedulePeriod       int16
	InSchema             types.Type
	OutSchema            types.Type
	Filter               *Where
	Transformation       Transformation
	Query                string
	Path                 string
	Sheet                string
	Compression          Compression
	OrderBy              string
	FormatSettings       []byte
	ExportMode           ExportMode
	Matching             Matching
	UpdateOnDuplicates   bool
	TableName            string
	TableKey             string
	IdentityColumn       string
	LastChangeTimeColumn string
	LastChangeTimeFormat string
	Reload               bool
	Incremental          bool
	Health               Health
}

type Matching struct {
	In  string
	Out string
}

// Language represents a transformation language.
type Language int

const (
	JavaScript Language = iota
	Python
)

// Scan implements the sql.Scanner interface.
func (lang *Language) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Language value", src)
	}
	switch s {
	case "JavaScript":
		*lang = JavaScript
	case "Python":
		*lang = Python
	default:
		return fmt.Errorf("invalid state.Language: %s", s)
	}
	return nil
}

func (lang Language) String() string {
	switch lang {
	case JavaScript:
		return "JavaScript"
	case Python:
		return "Python"
	}
	panic("invalid language")
}

// Transformation represents a transformation.
type Transformation struct {
	Mapping  map[string]string
	Function *TransformationFunction
	InPaths  []string
	OutPaths []string
}

// TransformationFunction represents a transformation function.
type TransformationFunction struct {
	ID           string
	Version      string
	Language     Language
	Source       string
	PreserveJSON bool
}

// ExportMode represents one of the three export modes.
type ExportMode string

const (
	CreateOnly     ExportMode = "CreateOnly"
	UpdateOnly     ExportMode = "UpdateOnly"
	CreateOrUpdate ExportMode = "CreateOrUpdate"
)

// ActionExecution represents an action execution.
type ActionExecution struct {
	mu          *sync.Mutex
	ID          int
	node        *uuid.UUID
	action      *Action
	Incremental bool
	Cursor      time.Time
	StartTime   time.Time
}

// Action returns the action of the execution.
func (ex *ActionExecution) Action() *Action {
	ex.mu.Lock()
	a := ex.action
	ex.mu.Unlock()
	return a
}

// Node returns the node on which the execution is currently running.
// The boolean return value indicates whether the execution is taking place on a
// node.
func (ex *ActionExecution) Node() (uuid.UUID, bool) {
	ex.mu.Lock()
	node := ex.node
	ex.mu.Unlock()
	if node == nil {
		return uuid.UUID{}, false
	}
	return *node, true
}

// Connection returns the connection of the action.
func (action *Action) Connection() *Connection {
	action.mu.Lock()
	c := action.connection
	action.mu.Unlock()
	return c
}

// Execution returns the execution of the action.
// The boolean return value reports whether the action is running.
func (action *Action) Execution() (*ActionExecution, bool) {
	action.mu.Lock()
	ex := action.execution
	action.mu.Unlock()
	return ex, ex != nil
}

// PropertiesToUnset returns the identity properties of the action that should
// be unset. It is non-nil for source actions on users.
func (action *Action) PropertiesToUnset() []string {
	action.mu.Lock()
	c := action.propertiesToUnset
	action.mu.Unlock()
	return c
}

// Format returns the format connector of the action.
func (action *Action) Format() *Connector {
	action.mu.Lock()
	c := action.format
	action.mu.Unlock()
	return c
}
