// Copyright 2025 Open2b. All rights reserved.
// Use of this source code is governed by an Elastic License 2.0
// that can be found in the LICENSE file.

package meergotester

import (
	"context"
	"crypto/tls"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"math"
	"net"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/meergo/meergo/cmd"
	"github.com/meergo/meergo/core"
	"github.com/meergo/meergo/core/types"
	"github.com/meergo/meergo/test/testimages"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/testcontainers/testcontainers-go"
	_postgres "github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/wait"
)

// launchMeergoExternally determines if Meergo should be launched externally
// when testing.
//
//   - Set this to true when testing Meergo using 'go run ./commit' or
//     'go test'.
//
//   - Set this to false when debugging a single Meergo test.
const launchMeergoExternally = true

// Meergo represents an instance of Meergo which responds to HTTP requests and
// exposes methods to make calls to the APIs.
type Meergo struct {
	cancel func()
	t      *testing.T
	// meergoRunning is used as a synchronization mechanism to wait for Meergo
	// to end its execution.
	// When Meergo is started -- both as an external process or as a goroutine
	// --, an empty channel should be assigned to it; when Meergo exits, the
	// channel must be closed; this allows the testing framework to wait for
	// Meergo to correctly exit before finishing the tests.
	meergoRunning          chan struct{}
	transformationsTempDir string
	httpClient             *http.Client
	ws                     int
	stopPostgresContainer  func() error
	stopWarehouseContainer func() error

	repo                 string
	needToGenerateAssets bool
	assetsGenerated      chan struct{}

	// Options.
	fileSystemRoot        string
	populateProfileSchema bool
}

var assetsAlreadyGenerated bool
var meergoAlreadyBuilt bool
var meergoAlreadyLaunched bool

// Addr returns the host (along with the port) on which the Meergo instance
// runs.
func (c *Meergo) Addr() string {
	return testsSettings.HTTP.Host + ":" + strconv.Itoa(testsSettings.HTTP.Port)
}

// NewMeergoInstance initializes a new instance of Meergo for testing.
//
// After initializing an instance, its options can be set (via
// [PopulateProfileSchema] and [SetFileSystemRoot]) and finally the instance can be
// started with the [Start] method.
func NewMeergoInstance(t *testing.T) *Meergo {

	if !launchMeergoExternally {
		if meergoAlreadyLaunched {
			msg := "aborting tests: you are executing more than one test, consequently the 'launchMeergoExternally'" +
				" constant cannot be false. It can be false only when executing a single test"
			t.Fatal(msg)
		}
		meergoAlreadyLaunched = true
	}

	ctx := context.Background()

	c := Meergo{
		t:                     t,
		populateProfileSchema: true,
	}

	// Determine the root of the repository.
	var err error
	c.repo, err = filepath.Abs("../")
	if err != nil {
		t.Fatal(err)
	}
	_, err = os.Stat(filepath.Join(c.repo, "go.mod"))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			t.Fatal("file 'go.mod' not found, cannot determine root directory where to build Meergo")
		}
		t.Fatal(err)
	}

	// If Meergo is run inside the testing process, it is necessary to generate
	// the assets. If it is run externally, the assets are generated separately,
	// when Meergo is compiled, so there is no need to compile them.
	const needToGenerateAssets = !launchMeergoExternally
	if needToGenerateAssets {
		c.assetsGenerated = make(chan struct{}, 1)
		go func() {
			// Generate the assets, if not already generated by another test
			// executed in this process.
			if !assetsAlreadyGenerated {
				log.Print("generating Meergo assets")
				err := generateAssets(ctx, c.repo)
				if err != nil {
					panic(fmt.Sprintf("cannot generate Meergo assets: %s", err))
				}
				log.Print("assets generated")
				assetsAlreadyGenerated = true
			}
			c.assetsGenerated <- struct{}{}
		}()
	}

	// Create a temporary directory that will hold the function files.
	transformationsTempDir, err := os.MkdirTemp("", "meergo-tests-python-function-*")
	if err != nil {
		t.Fatalf("cannot create temporary directory for Python function files: %s", err)
	}
	c.transformationsTempDir = transformationsTempDir

	return &c
}

// PopulateProfileSchema sets whether the profile schema should be populated
// extensively (populate = true), or simply the minimal profile schema should be
// used (populate = false).
//
// By default, if this method is not called before calling [Start], the option
// is considered true.
func (c *Meergo) PopulateProfileSchema(populate bool) {
	c.populateProfileSchema = populate
}

// SetFileSystemRoot sets the root of the File System connections; the value set
// here will be passed to Meergo via the MEERGO_CONNECTOR_FILESYSTEM_ROOT
// environment variable.
func (c *Meergo) SetFileSystemRoot(root string) {
	c.fileSystemRoot = root
}

// Start starts the Meergo instance.
//
// After calling this method, the [Stop] method must be called to stop the
// instance and shutdown the server.
func (c *Meergo) Start() {

	ctx := context.Background()

	// In case of an error during the starting of Meergo, stop it.
	var initOk bool
	defer func() {
		if !initOk {
			c.Stop()
		}
	}()

	containersStarted := sync.WaitGroup{}
	containersStarted.Add(2)

	// Start the PostgreSQL container and set the global test settings.
	go func() {
		postgresContainer, err := _postgres.Run(ctx,
			testimages.PostgreSQL,
			_postgres.WithDatabase("test_postgres"),
			_postgres.WithUsername("test_postgres"),
			_postgres.WithPassword("test_postgres"),
			testcontainers.WithWaitStrategy(
				wait.ForLog("database system is ready to accept connections").
					WithOccurrence(2).
					WithStartupTimeout(60*time.Second)),
		)
		c.stopPostgresContainer = func() error {
			return testcontainers.TerminateContainer(postgresContainer)
		}
		if err != nil {
			panic(fmt.Sprintf("cannot start the PostgreSQL container: %s", err))
		}
		postgresHost, err := postgresContainer.Host(ctx)
		if err != nil {
			panic(err)
		}
		postgresPort, err := postgresContainer.MappedPort(ctx, "5432/tcp")
		if err != nil {
			panic(err)
		}
		testsSettingsMu.Lock()
		testsSettings.Database.Host = postgresHost
		testsSettings.Database.Port = postgresPort.Int()
		testsSettingsMu.Unlock()
		containersStarted.Done()
	}()

	// Start the warehouse container and set the global test settings.
	go func() {
		warehouseContainer, err := _postgres.Run(ctx,
			testimages.PostgreSQL,
			_postgres.WithDatabase("test_warehouse"),
			_postgres.WithUsername("test_warehouse"),
			_postgres.WithPassword("test_warehouse"),
			testcontainers.WithWaitStrategy(
				wait.ForLog("database system is ready to accept connections").
					WithOccurrence(2).
					WithStartupTimeout(60*time.Second)),
		)
		c.stopWarehouseContainer = func() error {
			return testcontainers.TerminateContainer(warehouseContainer)
		}
		if err != nil {
			panic(fmt.Sprintf("cannot start the warehouse container: %s", err))
		}
		warehouseHost, err := warehouseContainer.Host(ctx)
		if err != nil {
			panic(err)
		}
		warehousePort, err := warehouseContainer.MappedPort(ctx, "5432/tcp")
		if err != nil {
			panic(err)
		}
		testsSettingsMu.Lock()
		testsSettings.Warehouse.Host = warehouseHost
		testsSettings.Warehouse.Port = warehousePort.Int()
		testsSettingsMu.Unlock()
		containersStarted.Done()
	}()

	// Wait for the containers to be started.
	c.t.Log("waiting for the containers to be started")
	containersStarted.Wait()
	c.t.Log("containers started")

	// Initialize the PostgreSQL database.
	err := initializePostgreSQLDatabase(ctx, testsSettings.Database)
	if err != nil {
		c.t.Fatalf("cannot initialize the PostgreSQL database: %s", err)
	}

	// Create the HTTP client.
	jar, err := cookiejar.New(nil)
	if err != nil {
		c.t.Fatalf("cannot create a cookie jar: %s", err)
	}
	c.httpClient = &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return errors.New("redirect")
		},
		Jar: jar,
	}

	// If the assets are needed, wait for them to be generated.
	if c.needToGenerateAssets {
		<-c.assetsGenerated
	}

	// Launch Meergo.
	ctxWithCancel, cancel := context.WithCancel(ctx)
	c.cancel = cancel

	if launchMeergoExternally {
		// Create, if necessary, the directory that will hold the Meergo
		// executable (as well as the other files needed for the execution).
		meergoDir := filepath.Join(c.repo, "test", "meergo-executable-for-tests")
		err = os.Mkdir(meergoDir, 0755)
		if err != nil && !errors.Is(err, os.ErrExist) {
			c.t.Fatal(err)
		}
		// In addition to the environment variables already present for the
		// process, add those needed to run Meergo.
		//
		// It is important to preserve the environment variables already present
		// because (1) it is the same thing we do when we test Meergo not as an
		// external process but "embedded" inside the current process, so this
		// makes the two test modes more consistent and (2) problems can occur
		// in running Meergo if certain system environment variables are not
		// provided (this for example gives errors on Windows).
		env := append(os.Environ(), []string{
			"MEERGO_EXTERNAL_ASSETS_URLS=https://assets.meergo.com/",
			"MEERGO_TELEMETRY_LEVEL=none",
			"MEERGO_HTTP_HOST=" + testsSettings.HTTP.Host,
			"MEERGO_HTTP_PORT=" + strconv.Itoa(testsSettings.HTTP.Port),
			"MEERGO_DB_HOST=" + testsSettings.Database.Host,
			"MEERGO_DB_PORT=" + strconv.Itoa(testsSettings.Database.Port),
			"MEERGO_DB_USERNAME=" + testsSettings.Database.Username,
			"MEERGO_DB_PASSWORD=" + testsSettings.Database.Password,
			"MEERGO_DB_DATABASE=" + testsSettings.Database.Database,
			"MEERGO_DB_SCHEMA=" + testsSettings.Database.Schema,
			"MEERGO_TRANSFORMERS_LOCAL_PYTHON_EXECUTABLE=" + testsSettings.PythonExecutable,
			"MEERGO_TRANSFORMERS_LOCAL_FUNCTIONS_DIR=" + c.transformationsTempDir,
			"MEERGO_CONNECTOR_FILESYSTEM_ROOT=" + c.fileSystemRoot,
		}...)
		if !meergoAlreadyBuilt {
			buildMeergo(c.t, c.repo, meergoDir)
			meergoAlreadyBuilt = true
		}
		go func() {
			c.meergoRunning = make(chan struct{})
			defer func() {
				close(c.meergoRunning)
			}()
			err := launchMeergo(ctxWithCancel, env)
			if err != nil && ctxWithCancel.Err() == nil {
				log.Printf("[error] %s", err)
			}
		}()
	} else {
		// Meergo settings.
		// Keep these in sync with the environment variables set above.
		setts := cmd.Settings{}
		setts.JavaScriptSDKURL = "https://cdn.meergo.com/meergo.min.js"
		setts.SentryTelemetryLevel = core.TelemetryLevelNone
		setts.ExternalAssetsURLs = []string{"https://assets.meergo.com/"}
		setts.PotentialConnectorsURL = "https://assets.meergo.com/admin/connectors/potentials.json"
		setts.HTTP.Host = testsSettings.HTTP.Host
		setts.HTTP.Port = testsSettings.HTTP.Port
		setts.HTTP.ExternalURL = fmt.Sprintf("http://%s:%d/", setts.HTTP.Host, setts.HTTP.Port)
		setts.HTTP.ExternalEventURL = setts.HTTP.ExternalURL + "api/v1/events"
		setts.DB.Host = testsSettings.Database.Host
		setts.DB.Port = testsSettings.Database.Port
		setts.DB.Username = testsSettings.Database.Username
		setts.DB.Password = testsSettings.Database.Password
		setts.DB.Database = testsSettings.Database.Database
		setts.DB.Schema = testsSettings.Database.Schema
		setts.Transformers.Local.PythonExecutable = testsSettings.PythonExecutable
		setts.Transformers.Local.FunctionsDir = c.transformationsTempDir
		err := os.Setenv("MEERGO_CONNECTOR_FILESYSTEM_ROOT", c.fileSystemRoot)
		if err != nil {
			c.t.Fatal(err)
		}
		err = validDatabaseNameForTests(setts.DB.Database)
		if err != nil {
			c.t.Fatal(err)
		}
		go func() {
			c.meergoRunning = make(chan struct{})
			defer func() {
				close(c.meergoRunning)
			}()
			assets := os.DirFS(filepath.Join(c.repo, "cmd", "meergo", "meergo-assets"))
			{
				// A random file, 'index.js.br', is opened just to verify if the
				// filesystem has been created correctly.
				f, err := assets.Open("index.js.br")
				if err != nil {
					log.Printf("cannot find file 'index.js.br' withing filesystem passed to Meergo, so maybe there is a problem with the tests and/or with the assets generation")
					return
				}
				_ = f.Close()
			}
			err = cmd.Run(ctxWithCancel, &setts, assets)
			if err != nil {
				log.Printf("[error] %s", err)
				return
			}
		}()
	}

	// Wait a second for Meergo to load.
	time.Sleep(1 * time.Second)

	addr := testsSettings.HTTP.Host + ":" + strconv.Itoa(testsSettings.HTTP.Port)

	// Wait until Meergo starts listening.
	attempts := 0
	for {
		select {
		case <-c.meergoRunning:
			c.t.Fatalf("Meergo has exited")
		default:
		}
		conn, err := net.DialTimeout("tcp", addr, 500*time.Millisecond)
		if err != nil {
			attempts++
			if attempts >= 30 {
				c.t.Fatalf("cannot connect to Meergo on %q. No response after %d connections attempts, aborting test", addr, attempts)
			}
			// Use an exponential backoff timeout.
			timeout := time.Duration(math.Exp(float64(attempts-1))*5) * time.Millisecond
			time.Sleep(timeout)
			continue
		}
		_ = conn.Close()
		break
	}

	// Login.
	err = c.login()
	if err != nil {
		c.t.Fatalf("cannot log in into the API: %s", err)
	}

	// Create the workspace and connect the warehouse.
	var profileSchema types.Type
	var uiPreferences UIPreferences
	if c.populateProfileSchema {
		profileSchema = testsProfileSchema
		uiPreferences.Profile.FirstName = "first_name"
		uiPreferences.Profile.LastName = "last_name"
		uiPreferences.Profile.Extra = "email"
	} else {
		profileSchema = minimalProfileSchema
	}
	id, err := c.createWorkspace("Test workspace", profileSchema, uiPreferences)
	if err != nil {
		c.t.Fatalf("cannot create workspace: %s", err)
	}
	c.ws = id

	// Wait some time for the leader election.
	time.Sleep(3 * time.Second)

	initOk = true
}

// CountEventsInWarehouse returns the counts of events stored in the "events"
// table of the testing data warehouse.
func (c *Meergo) CountEventsInWarehouse(ctx context.Context) int {
	pool, err := ConnectionPool(ctx, testsSettings.Warehouse)
	if err != nil {
		c.t.Fatalf("cannot open warehouse for executing query tests: %s", err)
	}
	defer pool.Close()
	var count int
	err = pool.QueryRow(ctx, `SELECT COUNT(*) AS "count" FROM "events"`).Scan(&count)
	if err != nil {
		c.t.Fatalf("cannot execute count query: %s", err)
	}
	return count
}

// Stop stops the execution of Meergo.
func (c *Meergo) Stop() {
	if c.cancel != nil {
		c.cancel()
	}
	if c.meergoRunning != nil {
		<-c.meergoRunning
	}
	if c.transformationsTempDir == "" {
		panic("BUG: transformationsTempDir not set")
	}
	err := os.RemoveAll(c.transformationsTempDir)
	if err != nil {
		log.Printf("cannot remove transformations temporary directory: %s", err)
		return
	}
	if c.stopPostgresContainer != nil {
		err := c.stopPostgresContainer()
		if err != nil {
			log.Printf("cannot stop PostgreSQL container: %s", err)
		}
	}
	if c.stopWarehouseContainer != nil {
		err := c.stopWarehouseContainer()
		if err != nil {
			log.Printf("cannot stop warehouse container: %s", err)
		}
	}
}

var minimalProfileSchema = types.Object([]types.Property{
	{Name: "email", Type: types.Text().WithCharLen(254), ReadOptional: true},
})

//go:embed tests_user_schema.json
var userSchemaJSON []byte

var testsProfileSchema types.Type

func init() {
	err := json.Unmarshal(userSchemaJSON, &testsProfileSchema)
	if err != nil {
		panic(fmt.Sprintf("invalid profile schema in file 'tests_user_schema.json': %s", err))
	}
}

func (c *Meergo) createWorkspace(name string, profileSchema types.Type, uiPreferences UIPreferences) (int, error) {
	req := map[string]any{
		"name":          name,
		"profileSchema": profileSchema,
		"warehouse": map[string]any{
			"name":     testsSettings.WarehouseName,
			"settings": testsSettings.Warehouse,
		},
		"uiPreferences": uiPreferences,
	}
	var response struct {
		ID int `json:"id"`
	}
	err := c.call("POST", "/api/v1/workspaces", req, &response)
	if err != nil {
		return 0, err
	}
	return response.ID, nil
}

func (c *Meergo) login() error {
	body := map[string]any{
		"email":    "acme@meergo.com",
		"password": "meergo-password",
	}
	return c.call("POST", "/api/v1/members/login", body, nil)
}

func initializePostgreSQLDatabase(ctx context.Context, dbSetts *DBSettings) error {
	err := validDatabaseNameForTests(dbSetts.Database)
	if err != nil {
		return err
	}
	pool, err := ConnectionPool(ctx, dbSetts)
	if err != nil {
		return fmt.Errorf("cannot establish connection to database: %s", err)
	}
	defer pool.Close()
	err = execQueries(ctx, pool, "../database/initialization/1 - postgres.sql")
	return err
}

// ExecQueryTestDatabase executes a query on the test database.
func (c *Meergo) ExecQueryTestDatabase(ctx context.Context, query string, args ...any) {
	pool, err := ConnectionPool(ctx, testsSettings.Database)
	if err != nil {
		c.t.Fatalf("cannot establish connection to database: %s", err)
	}
	defer pool.Close()
	_, err = pool.Exec(ctx, query, args...)
	if err != nil {
		c.t.Fatalf("query %q failed: %s", query, err)
	}
}

// QueryRowTestDatabase queries a row on the test database, scanning it into
// dest, which must be a pointer.
func (c *Meergo) QueryRowTestDatabase(ctx context.Context, dest any, query string, args ...any) {
	if reflect.TypeOf(dest).Kind() != reflect.Pointer {
		panic("dest must be a pointer")
	}
	pool, err := ConnectionPool(ctx, testsSettings.Database)
	if err != nil {
		c.t.Fatalf("cannot establish connection to database: %s", err)
	}
	defer pool.Close()
	err = pool.QueryRow(ctx, query, args...).Scan(dest)
	if err != nil {
		c.t.Fatalf("cannot scan result of QueryRow: %s", err)
	}
}

// WorkspaceID returns the ID of the workspace on which the instance of Meergo
// operates.
func (c *Meergo) WorkspaceID() int {
	return c.ws
}

// execQueries executes on db the queries read from queriesFile, separated by a
// ";" character and a newline.
func execQueries(ctx context.Context, pool *pgxpool.Pool, queriesFile string) error {

	content, err := os.ReadFile(queriesFile)
	if err != nil {
		abs, err2 := filepath.Abs(queriesFile)
		if err2 != nil {
			log.Panic(err)
		}
		return fmt.Errorf("cannot read %q: %s", abs, err)
	}

	queries := strings.Split(string(content), ";\n")

	// Recreate the schema from "1 - postgres.sql".
	for _, query := range queries {
		ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
		defer cancel()
		query = strings.TrimSpace(query)
		if query == "" {
			continue
		}
		_, err := pool.Exec(ctx, query)
		if err != nil {
			return err
		}
		cancel()
	}

	return nil

}

func ConnectionPool(ctx context.Context, s *DBSettings) (*pgxpool.Pool, error) {
	u := url.URL{
		Scheme: "postgres",
		User:   url.UserPassword(s.Username, s.Password),
		Host:   net.JoinHostPort(s.Host, strconv.Itoa(s.Port)),
		Path:   "/" + url.PathEscape(s.Database),
	}
	if s.Schema != "" {
		u.RawQuery = "search_path=" + url.QueryEscape(s.Schema)
	}
	config, err := pgxpool.ParseConfig(u.String())
	if err != nil {
		return nil, err
	}
	pool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		return nil, err
	}
	return pool, nil
}

var databaseNameRegexp = regexp.MustCompile(`^test_[a-zA-Z0-9_]+$`)

// validDatabaseNameForTests returns an error if name is not a valid database
// name for tests.
func validDatabaseNameForTests(name string) error {
	valid := databaseNameRegexp.MatchString(name)
	if !valid {
		return fmt.Errorf("invalid database name %q, it must match the regexp: ^test_[a-zA-Z0-9_]+$", name)
	}
	return nil
}
