//
// SPDX-License-Identifier: Elastic-2.0
//
//
// Copyright (c) 2023 Open2b
//

package meergotester

import (
	"context"
	"crypto/tls"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"math"
	"net"
	"net/http"
	"net/http/cookiejar"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/meergo/meergo/cmd"
	"github.com/meergo/meergo/core"
	"github.com/meergo/meergo/core/db"
	"github.com/meergo/meergo/testimages"
	"github.com/meergo/meergo/types"

	_ "github.com/meergo/meergo/connectors"
	_ "github.com/meergo/meergo/connectors/dummy"
	_ "github.com/meergo/meergo/warehouses"

	"github.com/testcontainers/testcontainers-go"
	_postgres "github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/wait"
)

// launchMeergoExternally determines if Meergo should be launched externally
// when testing.
//
//   - Set this to true when testing Meergo using 'go run ./commit' or
//     'go test'.
//
//   - Set this to false when debugging a single Meergo test.
const launchMeergoExternally = true

// Meergo represents an instance of Meergo which responds to HTTP requests and
// exposes methods to make calls to the APIs.
type Meergo struct {
	cancel func()
	t      *testing.T
	// meergoRunning is used as a synchronization mechanism to wait for Meergo
	// to end its execution.
	// When Meergo is started -- both as an external process or as a goroutine
	// --, an empty channel should be assigned to it; when Meergo exits, the
	// channel must be closed; this allows the testing framework to wait for
	// Meergo to correctly exit before finishing the tests.
	meergoRunning          chan struct{}
	transformationsTempDir string
	httpClient             *http.Client
	ws                     int
	stopPostgresContainer  func() error
	stopWarehouseContainer func() error
}

var assetsAlreadyGenerated bool
var meergoAlreadyBuilt bool
var meergoAlreadyLaunched bool

type TestingOption int

const (
	// DoNotPopulateUserSchema prevents the test from populating the user schema
	// with testing properties.
	DoNotPopulateUserSchema TestingOption = iota + 1
)

// Addr returns the host (along with the port) on which the Meergo instance
// runs.
func (c *Meergo) Addr() string {
	return testsSettings.HTTP.Host + ":" + strconv.Itoa(testsSettings.HTTP.Port)
}

// InitAndLaunch initializes and launches an instance of Meergo in a separate
// goroutine.
// After calling InitAndLaunch, the "Stop" method must be called on the returned
// instance of Meergo to stop the instance and shutdown the server.
func InitAndLaunch(t *testing.T, options ...TestingOption) *Meergo {

	if !launchMeergoExternally {
		if meergoAlreadyLaunched {
			msg := "aborting tests: you are executing more than one test, consequently the 'launchMeergoExternally'" +
				" constant cannot be false. It can be false only when executing a single test"
			t.Fatal(msg)
		}
		meergoAlreadyLaunched = true
	}

	ctx := context.Background()

	// Determine the root of the repository.
	repo, err := filepath.Abs("../")
	if err != nil {
		t.Fatal(err)
	}
	_, err = os.Stat(filepath.Join(repo, "go.mod"))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			t.Fatal("file 'go.mod' not found, cannot determine root directory where to build Meergo")
		}
		t.Fatal(err)
	}

	// Start a goroutine to generate assets, if necessary.
	//
	// The assets are generated both when Meergo is launched externally, as it
	// runs in production mode, and when Meergo is executed "embedded", since in
	// that case a filesystem is passed to the execution of Meergo that reads
	// from the "cmd/meergo/meergo-assets" directory.
	assetsGenerated := make(chan struct{}, 1)
	go func() {
		// Generate the assets, if not already generated by another test
		// executed in this process.
		if !assetsAlreadyGenerated {
			log.Print("generating Meergo assets")
			err := generateAssets(ctx, repo)
			if err != nil {
				panic(fmt.Sprintf("cannot generate meergo assets: %s", err))
			}
			log.Print("assets generated")
			assetsAlreadyGenerated = true
		}
		assetsGenerated <- struct{}{}
	}()

	// Determine the options.
	populateUserSchema := true
	for _, opt := range options {
		switch opt {
		case DoNotPopulateUserSchema:
			populateUserSchema = false
		default:
			panic("unexpected testing option %d")
		}
	}

	c := Meergo{t: t}

	// Create a temporary directory that will hold the function files.
	transformationsTempDir, err := os.MkdirTemp("", "meergo-tests-python-function-*")
	if err != nil {
		t.Fatalf("cannot create temporary directory for Python function files: %s", err)
	}
	c.transformationsTempDir = transformationsTempDir

	// In case of an error during the test initialization, stop Meergo.
	var initOk bool
	defer func() {
		if !initOk {
			c.Stop()
		}
	}()

	containersStarted := sync.WaitGroup{}
	containersStarted.Add(2)

	// Start the PostgreSQL container and set the global test settings.
	go func() {
		postgresContainer, err := _postgres.Run(ctx,
			testimages.PostgreSQL,
			_postgres.WithDatabase("test_postgres"),
			_postgres.WithUsername("test_postgres"),
			_postgres.WithPassword("test_postgres"),
			testcontainers.WithWaitStrategy(
				wait.ForLog("database system is ready to accept connections").
					WithOccurrence(2).
					WithStartupTimeout(60*time.Second)),
		)
		c.stopPostgresContainer = func() error {
			return testcontainers.TerminateContainer(postgresContainer)
		}
		if err != nil {
			panic(fmt.Sprintf("cannot start the PostgreSQL container: %s", err))
		}
		postgresHost, err := postgresContainer.Host(ctx)
		if err != nil {
			panic(err)
		}
		postgresPort, err := postgresContainer.MappedPort(ctx, "5432/tcp")
		if err != nil {
			panic(err)
		}
		testsSettingsMu.Lock()
		testsSettings.Database.Host = postgresHost
		testsSettings.Database.Port = postgresPort.Int()
		testsSettingsMu.Unlock()
		containersStarted.Done()
	}()

	// Start the warehouse container and set the global test settings.
	go func() {
		warehouseContainer, err := _postgres.Run(ctx,
			testimages.PostgreSQL,
			_postgres.WithDatabase("test_warehouse"),
			_postgres.WithUsername("test_warehouse"),
			_postgres.WithPassword("test_warehouse"),
			testcontainers.WithWaitStrategy(
				wait.ForLog("database system is ready to accept connections").
					WithOccurrence(2).
					WithStartupTimeout(60*time.Second)),
		)
		c.stopWarehouseContainer = func() error {
			return testcontainers.TerminateContainer(warehouseContainer)
		}
		if err != nil {
			panic(fmt.Sprintf("cannot start the warehouse container: %s", err))
		}
		warehouseHost, err := warehouseContainer.Host(ctx)
		if err != nil {
			panic(err)
		}
		warehousePort, err := warehouseContainer.MappedPort(ctx, "5432/tcp")
		if err != nil {
			panic(err)
		}
		testsSettingsMu.Lock()
		testsSettings.Warehouse.Host = warehouseHost
		testsSettings.Warehouse.Port = warehousePort.Int()
		testsSettingsMu.Unlock()
		containersStarted.Done()
	}()

	// Wait for the containers to be started.
	t.Log("waiting for the containers to be started")
	containersStarted.Wait()
	t.Log("containers started")

	// Initialize the PostgreSQL database.
	err = initializePostgreSQLDatabase(ctx, testsSettings.Database)
	if err != nil {
		t.Fatalf("cannot inizialize the PostgreSQL database: %s", err)
	}

	// Create the HTTP client.
	jar, err := cookiejar.New(nil)
	if err != nil {
		t.Fatalf("cannot create a cookie jar: %s", err)
	}
	c.httpClient = &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return errors.New("redirect")
		},
		Jar: jar,
	}

	// Wait for the assets to be generated.
	<-assetsGenerated

	// Launch Meergo.
	ctxWithCancel, cancel := context.WithCancel(ctx)
	c.cancel = cancel

	if launchMeergoExternally {
		// Create, if necessary, the directory that will hold the Meergo
		// executable (as well as the other files needed for the execution).
		meergoDir := filepath.Join(repo, "test", "meergo-executable-for-tests")
		err = os.Mkdir(meergoDir, 0755)
		if err != nil && !errors.Is(err, os.ErrExist) {
			t.Fatal(err)
		}
		// In addition to the environment variables already present for the
		// process, add those needed to run Meergo.
		//
		// It is important to preserve the environment variables already present
		// because (1) it is the same thing we do when we test Meergo not as an
		// external process but "embedded" inside the current process, so this
		// makes the two test modes more consistent and (2) problems can occur
		// in running Meergo if certain system environment variables are not
		// provided (this for example gives errors on Windows).
		env := append(os.Environ(), []string{
			"MEERGO_TELEMETRY_LEVEL=none",
			"MEERGO_HTTP_HOST=" + testsSettings.HTTP.Host,
			"MEERGO_HTTP_PORT=" + strconv.Itoa(testsSettings.HTTP.Port),
			"MEERGO_DB_HOST=" + testsSettings.Database.Host,
			"MEERGO_DB_PORT=" + strconv.Itoa(testsSettings.Database.Port),
			"MEERGO_DB_USERNAME=" + testsSettings.Database.Username,
			"MEERGO_DB_PASSWORD=" + testsSettings.Database.Password,
			"MEERGO_DB_DATABASE=" + testsSettings.Database.Database,
			"MEERGO_DB_SCHEMA=" + testsSettings.Database.Schema,
			"MEERGO_TRANSFORMATIONS_LOCAL_PYTHON_EXECUTABLE=" + testsSettings.PythonExecutable,
			"MEERGO_TRANSFORMATIONS_LOCAL_FUNCTIONS_DIR=" + transformationsTempDir,
		}...)
		if !meergoAlreadyBuilt {
			err := buildMeergo(ctx, repo, meergoDir)
			if err != nil {
				t.Fatalf("cannot build Meergo: %s", err)
			}
			meergoAlreadyBuilt = true
		}
		go func() {
			c.meergoRunning = make(chan struct{})
			defer func() {
				close(c.meergoRunning)
			}()
			err := launchMeergo(ctxWithCancel, env)
			if err != nil {
				select {
				case <-ctxWithCancel.Done():
				default:
					log.Printf("[error] %s", err)
				}
			}
		}()
	} else {
		// Meergo settings.
		// Keep these in sync with the environment variables set above.
		setts := cmd.Settings{}
		setts.SentryTelemetryLevel = core.TelemetryLevelNone
		setts.HTTP.Host = testsSettings.HTTP.Host
		setts.HTTP.Port = testsSettings.HTTP.Port
		setts.DB.Host = testsSettings.Database.Host
		setts.DB.Port = testsSettings.Database.Port
		setts.DB.Username = testsSettings.Database.Username
		setts.DB.Password = testsSettings.Database.Password
		setts.DB.Database = testsSettings.Database.Database
		setts.DB.Schema = testsSettings.Database.Schema
		setts.Transformations.Local.PythonExecutable = testsSettings.PythonExecutable
		setts.Transformations.Local.FunctionsDir = transformationsTempDir
		err = validDatabaseNameForTests(setts.DB.Database)
		if err != nil {
			t.Fatal(err)
		}
		go func() {
			c.meergoRunning = make(chan struct{})
			defer func() {
				close(c.meergoRunning)
			}()
			assets := os.DirFS(filepath.Join(repo, "cmd", "meergo", "meergo-assets"))
			{
				// A random file, 'index.js.br', is opened just to verify if the
				// filesystem has been created correctly.
				f, err := assets.Open("index.js.br")
				if err != nil {
					log.Printf("cannot find file 'index.js.br' withing filesystem passed to Meergo, so maybe there is a problem with the tests and/or with the assets generation")
					return
				}
				_ = f.Close()
			}
			err = cmd.Run(ctxWithCancel, &setts, assets)
			if err != nil {
				log.Printf("[error] %s", err)
				return
			}
		}()
	}

	// Wait a second for Meergo to load.
	time.Sleep(1 * time.Second)

	addr := testsSettings.HTTP.Host + ":" + strconv.Itoa(testsSettings.HTTP.Port)

	// Wait until Meergo starts listening.
	attempts := 0
	for {
		select {
		case <-c.meergoRunning:
			t.Fatalf("Meergo has exited")
		default:
		}
		conn, err := net.DialTimeout("tcp", addr, 500*time.Millisecond)
		if err != nil {
			attempts++
			if attempts >= 30 {
				t.Fatalf("cannot connect to Meergo on %q. No response after %d connections attempts, aborting test", addr, attempts)
			}
			// Use an exponential backoff timeout.
			timeout := time.Duration(math.Exp(float64(attempts-1))*5) * time.Millisecond
			time.Sleep(timeout)
			continue
		}
		_ = conn.Close()
		break
	}

	// Login.
	err = c.login()
	if err != nil {
		t.Fatalf("cannot log in into the API: %s", err)
	}

	// Create the workspace and connect the warehouse.
	var userSchema types.Type
	var displayedProperties DisplayedProperties
	if populateUserSchema {
		userSchema = testsUserSchema
		displayedProperties = DisplayedProperties{
			FirstName:   "first_name",
			LastName:    "last_name",
			Information: "email",
		}
	} else {
		userSchema = minimalUserSchema
	}
	id, err := c.createWorkspace("Test workspace", userSchema, displayedProperties)
	if err != nil {
		t.Fatalf("cannot create workspace: %s", err)
	}
	c.ws = id

	// Wait some time for the leader election.
	time.Sleep(3 * time.Second)

	initOk = true

	return &c
}

// CountEventsInWarehouse returns the counts of events stored in the "events"
// table of the testing data warehouse.
func (c *Meergo) CountEventsInWarehouse(ctx context.Context) int {
	db, err := db.Open(&db.Options{
		Host:     testsSettings.Warehouse.Host,
		Port:     testsSettings.Warehouse.Port,
		Username: testsSettings.Warehouse.Username,
		Password: testsSettings.Warehouse.Password,
		Database: testsSettings.Warehouse.Database,
		Schema:   testsSettings.Warehouse.Schema,
	})
	if err != nil {
		c.t.Fatalf("cannot open warehouse for executing query tests: %s", err)
	}
	defer db.Close()
	var count int
	err = db.QueryRow(ctx, `SELECT COUNT(*) AS "count" FROM "events"`).Scan(&count)
	if err != nil {
		c.t.Fatalf("cannot execute count query: %s", err)
	}
	return count
}

// Stop stops the execution of Meergo.
func (c *Meergo) Stop() {
	if c.cancel != nil {
		c.cancel()
	}
	if c.meergoRunning != nil {
		<-c.meergoRunning
	}
	if c.transformationsTempDir == "" {
		panic("BUG: transformationsTempDir not set")
	}
	err := os.RemoveAll(c.transformationsTempDir)
	if err != nil {
		log.Printf("cannot remove transformations temporary directory: %s", err)
		return
	}
	if c.stopPostgresContainer != nil {
		err := c.stopPostgresContainer()
		if err != nil {
			log.Printf("cannot stop PostgreSQL container: %s", err)
		}
	}
	if c.stopWarehouseContainer != nil {
		err := c.stopWarehouseContainer()
		if err != nil {
			log.Printf("cannot stop warehouse container: %s", err)
		}
	}
}

var minimalUserSchema = types.Object([]types.Property{
	{Name: "email", Type: types.Text().WithCharLen(254), ReadOptional: true},
})

//go:embed tests_user_schema.json
var userSchemaJSON []byte

var testsUserSchema types.Type

func init() {
	err := json.Unmarshal(userSchemaJSON, &testsUserSchema)
	if err != nil {
		panic(fmt.Sprintf("invalid user schema in file 'tests_user_schema.json': %s", err))
	}
}

func (c *Meergo) createWorkspace(name string, userSchema types.Type, displayedProperties DisplayedProperties) (int, error) {
	req := map[string]any{
		"name":                name,
		"userSchema":          userSchema,
		"displayedProperties": displayedProperties,
		"warehouse": map[string]any{
			"type":     testsSettings.WarehouseType,
			"settings": testsSettings.Warehouse,
		},
	}
	var response struct {
		ID int `json:"id"`
	}
	err := c.call("POST", "/api/v1/workspaces", req, &response)
	if err != nil {
		return 0, err
	}
	return response.ID, nil
}

func (c *Meergo) login() error {
	body := map[string]any{
		"email":    "acme@open2b.com",
		"password": "foopass2",
	}
	return c.call("POST", "/api/v1/members/login", body, nil)
}

func initializePostgreSQLDatabase(ctx context.Context, dbSetts *DBSettings) error {
	err := validDatabaseNameForTests(dbSetts.Database)
	if err != nil {
		return err
	}
	db, err := db.Open(&db.Options{
		Host:     dbSetts.Host,
		Port:     dbSetts.Port,
		Username: dbSetts.Username,
		Password: dbSetts.Password,
		Database: dbSetts.Database,
		Schema:   dbSetts.Schema,
	})
	if err != nil {
		return fmt.Errorf("cannot establish connection to database: %s", err)
	}
	defer db.Close()
	err = execQueries(ctx, db, "../database/PostgreSQL.sql")
	return err
}

// ExecQueryTestDatabase executes a query on the test database.
func (c *Meergo) ExecQueryTestDatabase(ctx context.Context, query string, args ...any) {
	db, err := db.Open(&db.Options{
		Host:     testsSettings.Database.Host,
		Port:     testsSettings.Database.Port,
		Username: testsSettings.Database.Username,
		Password: testsSettings.Database.Password,
		Database: testsSettings.Database.Database,
		Schema:   testsSettings.Database.Schema,
	})
	if err != nil {
		c.t.Fatalf("cannot open database for executing query tests: %s", err)
	}
	_, err = db.Exec(ctx, query, args...)
	if err != nil {
		c.t.Fatalf("query %q failed: %s", query, err)
	}
	db.Close()
}

// QueryRowTestDatabase queries a row on the test database, scanning it into
// dest, which must be a pointer.
func (c *Meergo) QueryRowTestDatabase(ctx context.Context, dest any, query string, args ...any) {
	if reflect.TypeOf(dest).Kind() != reflect.Pointer {
		panic("dest must be a pointer")
	}
	db, err := db.Open(&db.Options{
		Host:     testsSettings.Database.Host,
		Port:     testsSettings.Database.Port,
		Username: testsSettings.Database.Username,
		Password: testsSettings.Database.Password,
		Database: testsSettings.Database.Database,
		Schema:   testsSettings.Database.Schema,
	})
	if err != nil {
		c.t.Fatalf("cannot open database for executing query tests: %s", err)
	}
	err = db.QueryRow(ctx, query, args...).Scan(dest)
	if err != nil {
		c.t.Fatalf("cannot scan result of QueryRow: %s", err)
	}
	db.Close()
}

// WorkspaceID returns the ID of the workspace on which the instance of Meergo
// operates.
func (c *Meergo) WorkspaceID() int {
	return c.ws
}

// execQueries executes on db the queries read from queriesFile, separated by a
// ";" character and a newline.
func execQueries(ctx context.Context, db *db.DB, queriesFile string) error {

	content, err := os.ReadFile(queriesFile)
	if err != nil {
		abs, err2 := filepath.Abs(queriesFile)
		if err2 != nil {
			log.Panic(err)
		}
		return fmt.Errorf("cannot read %q: %s", abs, err)
	}

	queries := strings.Split(string(content), ";\n")

	// Recreate the schema from "PostgreSQL.sql".
	for _, query := range queries {
		ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
		defer cancel()
		query = strings.TrimSpace(query)
		if query == "" {
			continue
		}
		_, err := db.Exec(ctx, query)
		if err != nil {
			return err
		}
		cancel()
	}

	return nil

}

var databaseNameRegexp = regexp.MustCompile(`^test_[a-zA-Z0-9_]+$`)

// validDatabaseNameForTests returns an error if name is not a valid database
// name for tests.
func validDatabaseNameForTests(name string) error {
	valid := databaseNameRegexp.MatchString(name)
	if !valid {
		return fmt.Errorf("invalid database name %q, it must match the regexp: ^test_[a-zA-Z0-9_]+$", name)
	}
	return nil
}
