CREATE TABLE IF NOT EXISTS "_DESTINATIONS_USERS" (
    "__ACTION__" INT NOT NULL,
    "__USER__" VARCHAR NOT NULL DEFAULT '',
    "__PROPERTY__" VARCHAR NOT NULL,
    PRIMARY KEY ("__ACTION__", "__USER__")
);
