CREATE TABLE IF NOT EXISTS "_DESTINATIONS_USERS" (
    "__ACTION__" INT NOT NULL,
    "__EXTERNAL_ID__" VARCHAR NOT NULL DEFAULT '',
    "__OUT_MATCHING_VALUE__" VARCHAR NOT NULL,
    PRIMARY KEY ("__ACTION__", "__EXTERNAL_ID__")
);
