CREATE TABLE IF NOT EXISTS "_operations" (
    "id" INT AUTOINCREMENT START 0 INCREMENT 1 ORDER,
    "operation" VARCHAR NOT NULL,
    "start_time" TIMESTAMP_NTZ DEFAULT NULL,
    "end_time" TIMESTAMP_NTZ DEFAULT NULL,
    "users_version" INT DEFAULT NULL,
    PRIMARY KEY ("id")
);