CREATE TABLE IF NOT EXISTS "_OPERATIONS" (
    "ID" INT AUTOINCREMENT START 0 INCREMENT 1 ORDER,
    "OPERATION" VARCHAR NOT NULL,
    "START_TIME" TIMESTAMP_NTZ DEFAULT NULL,
    "END_TIME" TIMESTAMP_NTZ DEFAULT NULL,
    "USERS_VERSION" INT DEFAULT NULL,
    PRIMARY KEY ("ID")
);