CREATE TABLE IF NOT EXISTS "_OPERATIONS2" (
    "ID" VARCHAR NOT NULL,
    "OPERATION_TYPE" VARCHAR NOT NULL,
    "COMPLETED_AT" TIMESTAMP_NTZ,
    "ERROR" VARCHAR NOT NULL DEFAULT '',
    PRIMARY KEY ("ID")
);