CREATE TABLE IF NOT EXISTS "KRENALIS_SIMULATED_ACCOUNT_RECORDS" (
    "SIMULATED_ACCOUNT_ID" VARCHAR NOT NULL,
    "EXTERNAL_ID" VARCHAR NOT NULL,
    "DATA" VARIANT NOT NULL,
    PRIMARY KEY ("SIMULATED_ACCOUNT_ID", "EXTERNAL_ID")
);
