CREATE TABLE IF NOT EXISTS "_USER_IDENTITIES" (
    "__PK__" INT AUTOINCREMENT START 0 INCREMENT 1 ORDER,
    "__ACTION__" INT NOT NULL,
    "__IS_ANONYMOUS__" BOOLEAN NOT NULL DEFAULT FALSE,
    "__IDENTITY_ID__" VARCHAR NOT NULL,
    "__CONNECTION__" INT NOT NULL,
    "__ANONYMOUS_IDS__" ARRAY,
    "__LAST_CHANGE_TIME__" TIMESTAMP_NTZ NOT NULL,
    "__EXECUTION__" INT,
    "__GID__" VARCHAR(36),
    "__CLUSTER__" INT AUTOINCREMENT START 0 INCREMENT 1 ORDER,
    "EMAIL" VARCHAR(300),
    PRIMARY KEY ("__PK__")
);
