interface CurrencyOption {
	code: string;
	name: string;
	symbol?: string;
}

// Keep the codes synchronized with IsValidCurrencyCode in tools/validation/currency.go.
const COMMON_CURRENCY_OPTION_COUNT = 5;
const CURRENCY_OPTIONS: CurrencyOption[] = [
	{ code: 'USD', name: 'US dollar', symbol: '$' },
	{ code: 'EUR', name: 'Euro', symbol: '€' },
	{ code: 'GBP', name: 'British pound', symbol: '£' },
	{ code: 'JPY', name: 'Japanese yen', symbol: '¥' },
	{ code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
	{ code: 'AED', name: 'United Arab Emirates Dirham' },
	{ code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
	{ code: 'ALL', name: 'Albanian Lek' },
	{ code: 'AMD', name: 'Armenian Dram', symbol: '֏' },
	{ code: 'ANG', name: 'Netherlands Antillean Guilder' },
	{ code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz' },
	{ code: 'ARS', name: 'Argentine Peso', symbol: '$' },
	{ code: 'AUD', name: 'Australian Dollar', symbol: '$' },
	{ code: 'AWG', name: 'Aruban Florin' },
	{ code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼' },
	{ code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM' },
	{ code: 'BBD', name: 'Barbadian Dollar', symbol: '$' },
	{ code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
	{ code: 'BGN', name: 'Bulgarian Lev' },
	{ code: 'BHD', name: 'Bahraini Dinar' },
	{ code: 'BIF', name: 'Burundian Franc' },
	{ code: 'BMD', name: 'Bermudan Dollar', symbol: '$' },
	{ code: 'BND', name: 'Brunei Dollar', symbol: '$' },
	{ code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs' },
	{ code: 'BOV', name: 'Bolivian Mvdol' },
	{ code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
	{ code: 'BSD', name: 'Bahamian Dollar', symbol: '$' },
	{ code: 'BTN', name: 'Bhutanese Ngultrum' },
	{ code: 'BWP', name: 'Botswanan Pula', symbol: 'P' },
	{ code: 'BYN', name: 'Belarusian Ruble' },
	{ code: 'BZD', name: 'Belize Dollar', symbol: '$' },
	{ code: 'CAD', name: 'Canadian Dollar', symbol: '$' },
	{ code: 'CDF', name: 'Congolese Franc' },
	{ code: 'CHE', name: 'WIR Euro' },
	{ code: 'CHF', name: 'Swiss franc' },
	{ code: 'CHW', name: 'WIR Franc' },
	{ code: 'CLF', name: 'Chilean Unit of Account (UF)' },
	{ code: 'CLP', name: 'Chilean Peso', symbol: '$' },
	{ code: 'COP', name: 'Colombian Peso', symbol: '$' },
	{ code: 'COU', name: 'Colombian Real Value Unit' },
	{ code: 'CRC', name: 'Costa Rican Colón', symbol: '₡' },
	{ code: 'CUP', name: 'Cuban Peso', symbol: '$' },
	{ code: 'CVE', name: 'Cape Verdean Escudo' },
	{ code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
	{ code: 'DJF', name: 'Djiboutian Franc' },
	{ code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
	{ code: 'DOP', name: 'Dominican Peso', symbol: '$' },
	{ code: 'DZD', name: 'Algerian Dinar' },
	{ code: 'EGP', name: 'Egyptian Pound', symbol: 'E£' },
	{ code: 'ERN', name: 'Eritrean Nakfa' },
	{ code: 'ETB', name: 'Ethiopian Birr' },
	{ code: 'FJD', name: 'Fijian Dollar', symbol: '$' },
	{ code: 'FKP', name: 'Falkland Islands Pound', symbol: '£' },
	{ code: 'GEL', name: 'Georgian Lari', symbol: '₾' },
	{ code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵' },
	{ code: 'GIP', name: 'Gibraltar Pound', symbol: '£' },
	{ code: 'GMD', name: 'Gambian Dalasi' },
	{ code: 'GNF', name: 'Guinean Franc', symbol: 'FG' },
	{ code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q' },
	{ code: 'GYD', name: 'Guyanaese Dollar', symbol: '$' },
	{ code: 'HKD', name: 'Hong Kong Dollar', symbol: '$' },
	{ code: 'HNL', name: 'Honduran Lempira', symbol: 'L' },
	{ code: 'HTG', name: 'Haitian Gourde' },
	{ code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
	{ code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
	{ code: 'ILS', name: 'Israeli New Shekel', symbol: '₪' },
	{ code: 'INR', name: 'Indian Rupee', symbol: '₹' },
	{ code: 'IQD', name: 'Iraqi Dinar' },
	{ code: 'IRR', name: 'Iranian Rial' },
	{ code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
	{ code: 'JMD', name: 'Jamaican Dollar', symbol: '$' },
	{ code: 'JOD', name: 'Jordanian Dinar' },
	{ code: 'KES', name: 'Kenyan Shilling' },
	{ code: 'KGS', name: 'Kyrgystani Som', symbol: '⃀' },
	{ code: 'KHR', name: 'Cambodian Riel', symbol: '៛' },
	{ code: 'KMF', name: 'Comorian Franc', symbol: 'CF' },
	{ code: 'KPW', name: 'North Korean Won', symbol: '₩' },
	{ code: 'KRW', name: 'South Korean Won', symbol: '₩' },
	{ code: 'KWD', name: 'Kuwaiti Dinar' },
	{ code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$' },
	{ code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
	{ code: 'LAK', name: 'Laotian Kip', symbol: '₭' },
	{ code: 'LBP', name: 'Lebanese Pound', symbol: 'L£' },
	{ code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs' },
	{ code: 'LRD', name: 'Liberian Dollar', symbol: '$' },
	{ code: 'LSL', name: 'Lesotho Loti' },
	{ code: 'LYD', name: 'Libyan Dinar' },
	{ code: 'MAD', name: 'Moroccan Dirham' },
	{ code: 'MDL', name: 'Moldovan Leu' },
	{ code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar' },
	{ code: 'MKD', name: 'Macedonian Denar' },
	{ code: 'MMK', name: 'Myanmar Kyat', symbol: 'K' },
	{ code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮' },
	{ code: 'MOP', name: 'Macanese Pataca' },
	{ code: 'MRU', name: 'Mauritanian Ouguiya' },
	{ code: 'MUR', name: 'Mauritian Rupee', symbol: 'Rs' },
	{ code: 'MVR', name: 'Maldivian Rufiyaa' },
	{ code: 'MWK', name: 'Malawian Kwacha' },
	{ code: 'MXN', name: 'Mexican Peso', symbol: '$' },
	{ code: 'MXV', name: 'Mexican Investment Unit' },
	{ code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
	{ code: 'MZN', name: 'Mozambican Metical' },
	{ code: 'NAD', name: 'Namibian Dollar', symbol: '$' },
	{ code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
	{ code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$' },
	{ code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
	{ code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs' },
	{ code: 'NZD', name: 'New Zealand Dollar', symbol: '$' },
	{ code: 'OMR', name: 'Omani Rial' },
	{ code: 'PAB', name: 'Panamanian Balboa' },
	{ code: 'PEN', name: 'Peruvian Sol' },
	{ code: 'PGK', name: 'Papua New Guinean Kina' },
	{ code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
	{ code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs' },
	{ code: 'PLN', name: 'Polish Zloty', symbol: 'zł' },
	{ code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲' },
	{ code: 'QAR', name: 'Qatari Riyal' },
	{ code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
	{ code: 'RSD', name: 'Serbian Dinar' },
	{ code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
	{ code: 'RWF', name: 'Rwandan Franc', symbol: 'RF' },
	{ code: 'SAR', name: 'Saudi Riyal' },
	{ code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$' },
	{ code: 'SCR', name: 'Seychellois Rupee' },
	{ code: 'SDG', name: 'Sudanese Pound' },
	{ code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
	{ code: 'SGD', name: 'Singapore Dollar', symbol: '$' },
	{ code: 'SHP', name: 'St. Helena Pound', symbol: '£' },
	{ code: 'SLE', name: 'Sierra Leonean Leone' },
	{ code: 'SLL', name: 'Sierra Leonean Leone (1964—2022)' },
	{ code: 'SOS', name: 'Somali Shilling' },
	{ code: 'SRD', name: 'Surinamese Dollar', symbol: '$' },
	{ code: 'SSP', name: 'South Sudanese Pound', symbol: '£' },
	{ code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db' },
	{ code: 'SVC', name: 'Salvadoran Colón' },
	{ code: 'SYP', name: 'Syrian Pound', symbol: '£' },
	{ code: 'SZL', name: 'Swazi Lilangeni' },
	{ code: 'THB', name: 'Thai Baht', symbol: '฿' },
	{ code: 'TJS', name: 'Tajikistani Somoni' },
	{ code: 'TMT', name: 'Turkmenistani Manat' },
	{ code: 'TND', name: 'Tunisian Dinar' },
	{ code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$' },
	{ code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
	{ code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: '$' },
	{ code: 'TWD', name: 'New Taiwan Dollar', symbol: '$' },
	{ code: 'TZS', name: 'Tanzanian Shilling' },
	{ code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
	{ code: 'UGX', name: 'Ugandan Shilling' },
	{ code: 'USN', name: 'US Dollar (Next day)' },
	{ code: 'UYI', name: 'Uruguayan Peso (Indexed Units)' },
	{ code: 'UYU', name: 'Uruguayan Peso', symbol: '$' },
	{ code: 'UYW', name: 'Uruguayan Nominal Wage Index Unit' },
	{ code: 'UZS', name: 'Uzbekistani Som' },
	{ code: 'VED', name: 'Bolívar Soberano' },
	{ code: 'VES', name: 'Venezuelan Bolívar' },
	{ code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
	{ code: 'VUV', name: 'Vanuatu Vatu' },
	{ code: 'WST', name: 'Samoan Tala' },
	{ code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA' },
	{ code: 'XAG', name: 'Silver' },
	{ code: 'XAU', name: 'Gold' },
	{ code: 'XBA', name: 'European Composite Unit' },
	{ code: 'XBB', name: 'European Monetary Unit' },
	{ code: 'XBC', name: 'European Unit of Account (XBC)' },
	{ code: 'XBD', name: 'European Unit of Account (XBD)' },
	{ code: 'XCD', name: 'East Caribbean Dollar', symbol: '$' },
	{ code: 'XDR', name: 'Special Drawing Rights' },
	{ code: 'XOF', name: 'West African CFA Franc', symbol: 'F CFA' },
	{ code: 'XPD', name: 'Palladium' },
	{ code: 'XPF', name: 'CFP Franc', symbol: 'CFPF' },
	{ code: 'XPT', name: 'Platinum' },
	{ code: 'XSU', name: 'Sucre' },
	{ code: 'XTS', name: 'Testing Currency Code' },
	{ code: 'XUA', name: 'ADB Unit of Account' },
	{ code: 'XXX', name: 'Unknown Currency', symbol: '¤' },
	{ code: 'YER', name: 'Yemeni Rial' },
	{ code: 'ZAR', name: 'South African Rand', symbol: 'R' },
	{ code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
	{ code: 'ZWL', name: 'Zimbabwean Dollar (2009–2024)' },
];

export { COMMON_CURRENCY_OPTION_COUNT, CURRENCY_OPTIONS };
