interface CurrencyOption {
	code: string;
	name: string;
	symbol?: string;
	minorUnitDigits: number | null;
}

// Keep the codes synchronized with IsValidCurrencyCode in tools/validation/currency.go.
// minorUnitDigits is the ISO 4217 minor unit; null means that it is not applicable.
const COMMON_CURRENCY_OPTION_COUNT = 5;
const CURRENCY_OPTIONS: CurrencyOption[] = [
	{ code: 'USD', name: 'US dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'EUR', name: 'Euro', symbol: '€', minorUnitDigits: 2 },
	{ code: 'GBP', name: 'British pound', symbol: '£', minorUnitDigits: 2 },
	{ code: 'JPY', name: 'Japanese yen', symbol: '¥', minorUnitDigits: 0 },
	{ code: 'CNY', name: 'Chinese Yuan', symbol: '¥', minorUnitDigits: 2 },
	{ code: 'AED', name: 'United Arab Emirates Dirham', minorUnitDigits: 2 },
	{ code: 'AFN', name: 'Afghan Afghani', symbol: '؋', minorUnitDigits: 2 },
	{ code: 'ALL', name: 'Albanian Lek', minorUnitDigits: 2 },
	{ code: 'AMD', name: 'Armenian Dram', symbol: '֏', minorUnitDigits: 2 },
	{ code: 'ANG', name: 'Netherlands Antillean Guilder', minorUnitDigits: 2 },
	{ code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', minorUnitDigits: 2 },
	{ code: 'ARS', name: 'Argentine Peso', symbol: '$', minorUnitDigits: 2 },
	{ code: 'AUD', name: 'Australian Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'AWG', name: 'Aruban Florin', minorUnitDigits: 2 },
	{ code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', minorUnitDigits: 2 },
	{ code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', minorUnitDigits: 2 },
	{ code: 'BBD', name: 'Barbadian Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', minorUnitDigits: 2 },
	{ code: 'BGN', name: 'Bulgarian Lev', minorUnitDigits: 2 },
	{ code: 'BHD', name: 'Bahraini Dinar', minorUnitDigits: 3 },
	{ code: 'BIF', name: 'Burundian Franc', minorUnitDigits: 0 },
	{ code: 'BMD', name: 'Bermudan Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'BND', name: 'Brunei Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', minorUnitDigits: 2 },
	{ code: 'BOV', name: 'Bolivian Mvdol', minorUnitDigits: 2 },
	{ code: 'BRL', name: 'Brazilian Real', symbol: 'R$', minorUnitDigits: 2 },
	{ code: 'BSD', name: 'Bahamian Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'BTN', name: 'Bhutanese Ngultrum', minorUnitDigits: 2 },
	{ code: 'BWP', name: 'Botswanan Pula', symbol: 'P', minorUnitDigits: 2 },
	{ code: 'BYN', name: 'Belarusian Ruble', minorUnitDigits: 2 },
	{ code: 'BZD', name: 'Belize Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'CAD', name: 'Canadian Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'CDF', name: 'Congolese Franc', minorUnitDigits: 2 },
	{ code: 'CHE', name: 'WIR Euro', minorUnitDigits: 2 },
	{ code: 'CHF', name: 'Swiss franc', minorUnitDigits: 2 },
	{ code: 'CHW', name: 'WIR Franc', minorUnitDigits: 2 },
	{ code: 'CLF', name: 'Chilean Unit of Account (UF)', minorUnitDigits: 4 },
	{ code: 'CLP', name: 'Chilean Peso', symbol: '$', minorUnitDigits: 0 },
	{ code: 'COP', name: 'Colombian Peso', symbol: '$', minorUnitDigits: 2 },
	{ code: 'COU', name: 'Colombian Real Value Unit', minorUnitDigits: 2 },
	{ code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', minorUnitDigits: 2 },
	{ code: 'CUP', name: 'Cuban Peso', symbol: '$', minorUnitDigits: 2 },
	{ code: 'CVE', name: 'Cape Verdean Escudo', minorUnitDigits: 2 },
	{ code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', minorUnitDigits: 2 },
	{ code: 'DJF', name: 'Djiboutian Franc', minorUnitDigits: 0 },
	{ code: 'DKK', name: 'Danish Krone', symbol: 'kr', minorUnitDigits: 2 },
	{ code: 'DOP', name: 'Dominican Peso', symbol: '$', minorUnitDigits: 2 },
	{ code: 'DZD', name: 'Algerian Dinar', minorUnitDigits: 2 },
	{ code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', minorUnitDigits: 2 },
	{ code: 'ERN', name: 'Eritrean Nakfa', minorUnitDigits: 2 },
	{ code: 'ETB', name: 'Ethiopian Birr', minorUnitDigits: 2 },
	{ code: 'FJD', name: 'Fijian Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', minorUnitDigits: 2 },
	{ code: 'GEL', name: 'Georgian Lari', symbol: '₾', minorUnitDigits: 2 },
	{ code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', minorUnitDigits: 2 },
	{ code: 'GIP', name: 'Gibraltar Pound', symbol: '£', minorUnitDigits: 2 },
	{ code: 'GMD', name: 'Gambian Dalasi', minorUnitDigits: 2 },
	{ code: 'GNF', name: 'Guinean Franc', symbol: 'FG', minorUnitDigits: 0 },
	{ code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', minorUnitDigits: 2 },
	{ code: 'GYD', name: 'Guyanaese Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'HNL', name: 'Honduran Lempira', symbol: 'L', minorUnitDigits: 2 },
	{ code: 'HTG', name: 'Haitian Gourde', minorUnitDigits: 2 },
	{ code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', minorUnitDigits: 2 },
	{ code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', minorUnitDigits: 2 },
	{ code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', minorUnitDigits: 2 },
	{ code: 'INR', name: 'Indian Rupee', symbol: '₹', minorUnitDigits: 2 },
	{ code: 'IQD', name: 'Iraqi Dinar', minorUnitDigits: 3 },
	{ code: 'IRR', name: 'Iranian Rial', minorUnitDigits: 2 },
	{ code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', minorUnitDigits: 0 },
	{ code: 'JMD', name: 'Jamaican Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'JOD', name: 'Jordanian Dinar', minorUnitDigits: 3 },
	{ code: 'KES', name: 'Kenyan Shilling', minorUnitDigits: 2 },
	{ code: 'KGS', name: 'Kyrgystani Som', symbol: '⃀', minorUnitDigits: 2 },
	{ code: 'KHR', name: 'Cambodian Riel', symbol: '៛', minorUnitDigits: 2 },
	{ code: 'KMF', name: 'Comorian Franc', symbol: 'CF', minorUnitDigits: 0 },
	{ code: 'KPW', name: 'North Korean Won', symbol: '₩', minorUnitDigits: 2 },
	{ code: 'KRW', name: 'South Korean Won', symbol: '₩', minorUnitDigits: 0 },
	{ code: 'KWD', name: 'Kuwaiti Dinar', minorUnitDigits: 3 },
	{ code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', minorUnitDigits: 2 },
	{ code: 'LAK', name: 'Laotian Kip', symbol: '₭', minorUnitDigits: 2 },
	{ code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', minorUnitDigits: 2 },
	{ code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', minorUnitDigits: 2 },
	{ code: 'LRD', name: 'Liberian Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'LSL', name: 'Lesotho Loti', minorUnitDigits: 2 },
	{ code: 'LYD', name: 'Libyan Dinar', minorUnitDigits: 3 },
	{ code: 'MAD', name: 'Moroccan Dirham', minorUnitDigits: 2 },
	{ code: 'MDL', name: 'Moldovan Leu', minorUnitDigits: 2 },
	{ code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', minorUnitDigits: 2 },
	{ code: 'MKD', name: 'Macedonian Denar', minorUnitDigits: 2 },
	{ code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', minorUnitDigits: 2 },
	{ code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', minorUnitDigits: 2 },
	{ code: 'MOP', name: 'Macanese Pataca', minorUnitDigits: 2 },
	{ code: 'MRU', name: 'Mauritanian Ouguiya', minorUnitDigits: 2 },
	{ code: 'MUR', name: 'Mauritian Rupee', symbol: 'Rs', minorUnitDigits: 2 },
	{ code: 'MVR', name: 'Maldivian Rufiyaa', minorUnitDigits: 2 },
	{ code: 'MWK', name: 'Malawian Kwacha', minorUnitDigits: 2 },
	{ code: 'MXN', name: 'Mexican Peso', symbol: '$', minorUnitDigits: 2 },
	{ code: 'MXV', name: 'Mexican Investment Unit', minorUnitDigits: 2 },
	{ code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', minorUnitDigits: 2 },
	{ code: 'MZN', name: 'Mozambican Metical', minorUnitDigits: 2 },
	{ code: 'NAD', name: 'Namibian Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'NGN', name: 'Nigerian Naira', symbol: '₦', minorUnitDigits: 2 },
	{ code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', minorUnitDigits: 2 },
	{ code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', minorUnitDigits: 2 },
	{ code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs', minorUnitDigits: 2 },
	{ code: 'NZD', name: 'New Zealand Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'OMR', name: 'Omani Rial', minorUnitDigits: 3 },
	{ code: 'PAB', name: 'Panamanian Balboa', minorUnitDigits: 2 },
	{ code: 'PEN', name: 'Peruvian Sol', minorUnitDigits: 2 },
	{ code: 'PGK', name: 'Papua New Guinean Kina', minorUnitDigits: 2 },
	{ code: 'PHP', name: 'Philippine Peso', symbol: '₱', minorUnitDigits: 2 },
	{ code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs', minorUnitDigits: 2 },
	{ code: 'PLN', name: 'Polish Zloty', symbol: 'zł', minorUnitDigits: 2 },
	{ code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', minorUnitDigits: 0 },
	{ code: 'QAR', name: 'Qatari Riyal', minorUnitDigits: 2 },
	{ code: 'RON', name: 'Romanian Leu', symbol: 'lei', minorUnitDigits: 2 },
	{ code: 'RSD', name: 'Serbian Dinar', minorUnitDigits: 2 },
	{ code: 'RUB', name: 'Russian Ruble', symbol: '₽', minorUnitDigits: 2 },
	{ code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', minorUnitDigits: 0 },
	{ code: 'SAR', name: 'Saudi Riyal', minorUnitDigits: 2 },
	{ code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'SCR', name: 'Seychellois Rupee', minorUnitDigits: 2 },
	{ code: 'SDG', name: 'Sudanese Pound', minorUnitDigits: 2 },
	{ code: 'SEK', name: 'Swedish Krona', symbol: 'kr', minorUnitDigits: 2 },
	{ code: 'SGD', name: 'Singapore Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'SHP', name: 'St. Helena Pound', symbol: '£', minorUnitDigits: 2 },
	{ code: 'SLE', name: 'Sierra Leonean Leone', minorUnitDigits: 2 },
	{ code: 'SLL', name: 'Sierra Leonean Leone (1964—2022)', minorUnitDigits: 2 },
	{ code: 'SOS', name: 'Somali Shilling', minorUnitDigits: 2 },
	{ code: 'SRD', name: 'Surinamese Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'SSP', name: 'South Sudanese Pound', symbol: '£', minorUnitDigits: 2 },
	{ code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db', minorUnitDigits: 2 },
	{ code: 'SVC', name: 'Salvadoran Colón', minorUnitDigits: 2 },
	{ code: 'SYP', name: 'Syrian Pound', symbol: '£', minorUnitDigits: 2 },
	{ code: 'SZL', name: 'Swazi Lilangeni', minorUnitDigits: 2 },
	{ code: 'THB', name: 'Thai Baht', symbol: '฿', minorUnitDigits: 2 },
	{ code: 'TJS', name: 'Tajikistani Somoni', minorUnitDigits: 2 },
	{ code: 'TMT', name: 'Turkmenistani Manat', minorUnitDigits: 2 },
	{ code: 'TND', name: 'Tunisian Dinar', minorUnitDigits: 3 },
	{ code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', minorUnitDigits: 2 },
	{ code: 'TRY', name: 'Turkish Lira', symbol: '₺', minorUnitDigits: 2 },
	{ code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'TWD', name: 'New Taiwan Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'TZS', name: 'Tanzanian Shilling', minorUnitDigits: 2 },
	{ code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', minorUnitDigits: 2 },
	{ code: 'UGX', name: 'Ugandan Shilling', minorUnitDigits: 0 },
	{ code: 'USN', name: 'US Dollar (Next day)', minorUnitDigits: 2 },
	{ code: 'UYI', name: 'Uruguayan Peso (Indexed Units)', minorUnitDigits: 0 },
	{ code: 'UYU', name: 'Uruguayan Peso', symbol: '$', minorUnitDigits: 2 },
	{ code: 'UYW', name: 'Uruguayan Nominal Wage Index Unit', minorUnitDigits: 4 },
	{ code: 'UZS', name: 'Uzbekistani Som', minorUnitDigits: 2 },
	{ code: 'VED', name: 'Bolívar Soberano', minorUnitDigits: 2 },
	{ code: 'VES', name: 'Venezuelan Bolívar', minorUnitDigits: 2 },
	{ code: 'VND', name: 'Vietnamese Dong', symbol: '₫', minorUnitDigits: 0 },
	{ code: 'VUV', name: 'Vanuatu Vatu', minorUnitDigits: 0 },
	{ code: 'WST', name: 'Samoan Tala', minorUnitDigits: 2 },
	{ code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', minorUnitDigits: 0 },
	{ code: 'XAG', name: 'Silver', minorUnitDigits: null },
	{ code: 'XAU', name: 'Gold', minorUnitDigits: null },
	{ code: 'XBA', name: 'European Composite Unit', minorUnitDigits: null },
	{ code: 'XBB', name: 'European Monetary Unit', minorUnitDigits: null },
	{ code: 'XBC', name: 'European Unit of Account (XBC)', minorUnitDigits: null },
	{ code: 'XBD', name: 'European Unit of Account (XBD)', minorUnitDigits: null },
	{ code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', minorUnitDigits: 2 },
	{ code: 'XDR', name: 'Special Drawing Rights', minorUnitDigits: null },
	{ code: 'XOF', name: 'West African CFA Franc', symbol: 'F CFA', minorUnitDigits: 0 },
	{ code: 'XPD', name: 'Palladium', minorUnitDigits: null },
	{ code: 'XPF', name: 'CFP Franc', symbol: 'CFPF', minorUnitDigits: 0 },
	{ code: 'XPT', name: 'Platinum', minorUnitDigits: null },
	{ code: 'XSU', name: 'Sucre', minorUnitDigits: null },
	{ code: 'XTS', name: 'Testing Currency Code', minorUnitDigits: null },
	{ code: 'XUA', name: 'ADB Unit of Account', minorUnitDigits: null },
	{ code: 'XXX', name: 'Unknown Currency', symbol: '¤', minorUnitDigits: null },
	{ code: 'YER', name: 'Yemeni Rial', minorUnitDigits: 2 },
	{ code: 'ZAR', name: 'South African Rand', symbol: 'R', minorUnitDigits: 2 },
	{ code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', minorUnitDigits: 2 },
	{ code: 'ZWL', name: 'Zimbabwean Dollar (2009–2024)', minorUnitDigits: 2 },
];

export { COMMON_CURRENCY_OPTION_COUNT, CURRENCY_OPTIONS };
