encryptionKey: 6uA9ccQxZ+/1PlqXZFR49QZ0fnQDCNZIugyKwHv3WdkqcoIA3iSwuuj1yvM+f2cZFQ7Saqjq695Y0AP+rlZDOg== # Key for encryption (ensure it's securely stored)
terminationDelay: 1s # Delay before terminating the server or process

http:
    host: meergo # Server address
    port: 9090 # Port on which the server will listen
    tls:
        enabled: false # Whether TLS (HTTPS) is enabled
        certFile: /path/to/your/certificate.crt # Path to the TLS certificate
        keyFile: /path/to/your/private.key # Path to the TLS private key
    externalURL: http://127.0.0.1:9090/ # External URL exposed to the outside world
    cdnURL: # The address of the CDN serving the admin files and the JavaScript SDK. Can be left empty
    eventURL: # The address that receives the events, for example "https://my.meergo.example.com/api/v1/events". Can be left empty

db:
    host: db # PostgreSQL host address
    port: 5432 # PostgreSQL port
    username: meergo # PostgreSQL username
    password: meergo # PostgreSQL password
    database: meergo # PostgreSQL database
    schema: # PostgreSQL schema

smtp:
    host: # SMTP server host
    port: # SMTP server port
    user: # SMTP username
    pass: # SMTP password

transformations:
    local: # Local execution
        nodeExecutable: /usr/bin/node # Path to the Node.js executable
        pythonExecutable: /usr/bin/python # Path to the Python executable
        functionsDir: /bin/meergo-files/transformation-functions # Directory for local function source files

oauth:
    HubSpot:
        clientID: # OAuth client ID for HubSpot
        clientSecret: # OAuth client secret for HubSpot
    Mailchimp:
        clientID: # OAuth client ID for Mailchimp
        clientSecret: # OAuth client secret for Mailchimp

telemetry:
    enable: false # Enable telemetry for usage data collection
