

CREATE COLLATION case_insensitive (provider = icu, locale = 'und-u-ks-level2', deterministic = false);

CREATE TYPE action_target AS ENUM ('Event', 'User', 'Group');

CREATE TABLE organizations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(45) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
);

INSERT INTO organizations (name) VALUES ('ACME inc');

CREATE TYPE warehouse_mode AS ENUM ('Normal', 'Inspection', 'Maintenance');

CREATE TABLE workspaces (
    id integer NOT NULL,
    organization integer NOT NULL REFERENCES organizations ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    warehouse_type varchar NOT NULL,
    warehouse_mode warehouse_mode NOT NULL,
    warehouse_settings varchar(65535) NOT NULL,
    warehouse_mcp_settings varchar(65535) NOT NULL DEFAULT 'null'::jsonb,
    alter_user_schema_id uuid,
    alter_user_schema_schema jsonb NOT NULL DEFAULT 'null'::jsonb,
    alter_user_schema_primary_sources jsonb,
    alter_user_schema_operations jsonb,
    alter_user_schema_start_time timestamp(3),
    alter_user_schema_end_time timestamp(3),
    alter_user_schema_error varchar,
    user_schema jsonb NOT NULL DEFAULT 'null'::jsonb,
    resolve_identities_on_batch_import boolean NOT NULL DEFAULT false,
    identifiers text[] NOT NULL DEFAULT '{}',
    ir_id uuid,
    ir_start_time timestamp(3),
    ir_end_time timestamp(3),
    ui_user_profile_image varchar(100) NOT NULL DEFAULT '',
    ui_user_profile_first_name varchar(100) NOT NULL DEFAULT '',
    ui_user_profile_last_name varchar(100) NOT NULL DEFAULT '',
    ui_user_profile_extra varchar(100) NOT NULL DEFAULT '',
    actions_to_purge int[] NOT NULL DEFAULT '{}',
    PRIMARY KEY (id)
);

CREATE TABLE api_keys (
    id integer NOT NULL,
    organization integer NOT NULL REFERENCES organizations ON DELETE CASCADE,
    workspace integer REFERENCES workspaces ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    token varchar(43) NOT NULL UNIQUE,
    created_at timestamp(0) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TYPE connector_type AS ENUM ('App', 'Database', 'File', 'FileStorage', 'SDK', 'Stream');

CREATE TYPE role AS ENUM ('Source', 'Destination');

CREATE TYPE health AS ENUM ('Healthy', 'NoRecentData', 'RecentError');

CREATE TYPE compression AS ENUM ('', 'Zip', 'Gzip', 'Snappy');

CREATE TYPE strategy AS ENUM ('Conversion', 'Fusion', 'Isolation', 'Preservation');

CREATE TYPE sending_mode as ENUM ('Client', 'Server', 'ClientAndServer');

CREATE TABLE connections (
    id integer NOT NULL,
    workspace integer NOT NULL REFERENCES workspaces ON DELETE CASCADE,
    name varchar(100) NOT NULL DEFAULT '',
    connector varchar,
    role role NOT NULL,
    account integer NOT NULL DEFAULT 0,
    strategy strategy,
    sending_mode sending_mode,
    linked_connections integer[],
    settings varchar(65535),
    health health NOT NULL DEFAULT 'Healthy',
    PRIMARY KEY (id)
);

CREATE TYPE export_mode AS ENUM ('', 'CreateOnly', 'UpdateOnly', 'CreateOrUpdate');
CREATE TYPE transformation_language AS ENUM ('JavaScript', 'Python');

CREATE TABLE actions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    connection integer NOT NULL REFERENCES connections ON DELETE CASCADE,
    target action_target NOT NULL,
    event_type varchar(100) NOT NULL,
    name varchar(60) NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT FALSE,
    schedule_start smallint NOT NULL DEFAULT 0 CHECK (schedule_start >= 0 AND schedule_start < 1440),
    schedule_period smallint NOT NULL DEFAULT 0 CHECK(schedule_period IN (0, 5, 15, 30, 60, 120, 180, 360, 480, 720, 1440)),
    in_schema jsonb NOT NULL DEFAULT 'null'::jsonb,
    out_schema jsonb NOT NULL DEFAULT 'null'::jsonb,
    filter text NOT NULL DEFAULT '',
    transformation_mapping jsonb,
    transformation_id varchar(200) NOT NULL DEFAULT '',
    transformation_version varchar(128) NOT NULL DEFAULT '',
    transformation_language transformation_language NOT NULL,
    transformation_source text NOT NULL DEFAULT '',
    transformation_preserve_json boolean NOT NULL DEFAULT false,
    transformation_in_paths varchar[],
    transformation_out_paths varchar[],
    query text NOT NULL DEFAULT '',
    format varchar,
    path varchar(1024) NOT NULL DEFAULT '',
    sheet varchar(31) NOT NULL DEFAULT '',
    compression compression NOT NULL DEFAULT '',
    order_by varchar(1024) NOT NULL DEFAULT '',
    format_settings varchar(65535),
    export_mode export_mode NOT NULL DEFAULT '',
    matching_in text NOT NULL,
    matching_out text NOT NULL,
    update_on_duplicates boolean NOT NULL,
    table_name varchar(1024) NOT NULL DEFAULT '',
    table_key text NOT NULL,
    identity_column varchar(1024) NOT NULL DEFAULT '',
    last_change_time_column varchar(1024) NOT NULL DEFAULT '',
    last_change_time_format varchar(64) NOT NULL DEFAULT '',
    incremental boolean NOT NULL DEFAULT FALSE,
    cursor timestamp NOT NULL DEFAULT '0001-01-01 00:00:00+00',
    health health NOT NULL DEFAULT 'Healthy',
    properties_to_unset varchar[],
    PRIMARY KEY (id)
);

CREATE TABLE actions_executions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    action integer NOT NULL REFERENCES actions ON DELETE CASCADE,
    function varchar(200) NOT NULL DEFAULT '',
    node uuid,
    incremental boolean NOT NULL DEFAULT FALSE,
    cursor timestamp NOT NULL DEFAULT '0001-01-01 00:00:00+00',
    start_time timestamp NOT NULL,
    ping_time timestamp NOT NULL,
    end_time timestamp,
    passed_0 integer NOT NULL DEFAULT 0,
    passed_1 integer NOT NULL DEFAULT 0,
    passed_2 integer NOT NULL DEFAULT 0,
    passed_3 integer NOT NULL DEFAULT 0,
    passed_4 integer NOT NULL DEFAULT 0,
    passed_5 integer NOT NULL DEFAULT 0,
    failed_0 integer NOT NULL DEFAULT 0,
    failed_1 integer NOT NULL DEFAULT 0,
    failed_2 integer NOT NULL DEFAULT 0,
    failed_3 integer NOT NULL DEFAULT 0,
    failed_4 integer NOT NULL DEFAULT 0,
    failed_5 integer NOT NULL DEFAULT 0,
    error varchar NOT NULL DEFAULT '',
    PRIMARY KEY (id)
);

CREATE INDEX ON actions_executions (function)
    WHERE function != '' AND end_time IS NOT NULL;

CREATE TABLE actions_errors (
    action integer NOT NULL REFERENCES actions ON DELETE CASCADE,
    timeslot integer NOT NULL,
    step smallint NOT NULL,
    count integer NOT NULL,
    message varchar NOT NULL
);

CREATE INDEX ON actions_errors (action);
CREATE INDEX ON actions_errors (timeslot);
CREATE INDEX ON actions_errors (step);

CREATE TABLE actions_metrics (
    action integer NOT NULL REFERENCES actions ON DELETE CASCADE,
    timeslot integer NOT NULL,
    passed_0 integer NOT NULL,
    passed_1 integer NOT NULL,
    passed_2 integer NOT NULL,
    passed_3 integer NOT NULL,
    passed_4 integer NOT NULL,
    passed_5 integer NOT NULL,
    failed_0 integer NOT NULL,
    failed_1 integer NOT NULL,
    failed_2 integer NOT NULL,
    failed_3 integer NOT NULL,
    failed_4 integer NOT NULL,
    failed_5 integer NOT NULL,
    PRIMARY KEY (action, timeslot)
);

CREATE INDEX ON actions_metrics (action);
CREATE INDEX ON actions_metrics (timeslot);

CREATE TABLE discontinued_functions (
    id varchar(200) NOT NULL,
    discontinued_at timestamp(0) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE election (
    number integer NOT NULL,
    leader uuid NOT NULL,
    date timestamp NOT NULL,
    PRIMARY KEY (number)
);

INSERT INTO election (number, leader, date) VALUES (1, '00000000-0000-0000-0000-000000000000', '2023-01-01 00:00:00.000000');

CREATE TABLE event_write_keys (
    connection INT NOT NULL REFERENCES connections ON DELETE CASCADE,
    key char(32) NOT NULL,
    created_at timestamp NOT NULL,
    PRIMARY KEY (connection, key)
);

CREATE TYPE avatar_mime_type AS ENUM ('image/jpeg', 'image/png');

CREATE TYPE avatar AS (
    image bytea,
    mime_type avatar_mime_type
);

CREATE TABLE members (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    organization integer NOT NULL REFERENCES organizations ON DELETE CASCADE,
    name varchar(45) NOT NULL DEFAULT '',
    avatar avatar,
    email varchar(120) NOT NULL COLLATE case_insensitive,
    password varchar(72) NOT NULL DEFAULT '',
    invitation_token varchar(44) NOT NULL DEFAULT '',
    reset_password_token varchar(44) NOT NULL DEFAULT '',
    reset_password_token_created_at timestamp,
    created_at timestamp,
    UNIQUE (organization, email),
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX invitation_token_index ON members (invitation_token) WHERE invitation_token <> '';
CREATE UNIQUE INDEX reset_password_token_index ON members (reset_password_token) WHERE reset_password_token <> '';

INSERT INTO members (organization, name, avatar, email, password, created_at) VALUES (1, 'ACME inc', NULL, 'acme@open2b.com', '$2a$10$iMuokZyvwdAQOJJmJvG83eSGGWTV3DOjI2DRU6SjuLEuK.vknUJVC', '2024-01-01 00:00:00.000000'); -- Password: foopass2

CREATE TABLE user_schema_primary_sources (
    source integer NOT NULL REFERENCES connections ON DELETE CASCADE,
    path varchar NOT NULL,
    PRIMARY KEY (source, path)
);

CREATE TABLE accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    workspace integer NOT NULL REFERENCES workspaces ON DELETE CASCADE,
    connector varchar NOT NULL,
    code varchar(100) NOT NULL,
    access_token varchar(500) NOT NULL DEFAULT '',
    refresh_token varchar(500) NOT NULL DEFAULT '',
    expires_in timestamp(0),
    PRIMARY KEY (id)
);

CREATE INDEX ON accounts (connector);

CREATE TYPE notification_name AS ENUM (
    'CreateAPIKey',
    'CreateAction',
    'CreateConnection',
    'CreateEventWriteKey',
    'CreateWorkspace',
    'DeleteAPIKey',
    'DeleteAction',
    'DeleteConnection',
    'DeleteEventWriteKey',
    'DeleteWorkspace',
    'EndActionExecution',
    'EndAlterUserSchema',
    'EndIdentityResolution',
    'ExecuteAction',
    'LinkConnection',
    'PurgeActions',
    'RenameConnection',
    'RenameWorkspace',
    'SetAccount',
    'SetActionFormatSettings',
    'SetActionSchedulePeriod',
    'SetActionStatus',
    'SetConnectionSettings',
    'StartAlterUserSchema',
    'StartIdentityResolution',
    'UnlinkConnection',
    'UpdateAction',
    'UpdateConnection',
    'UpdateIdentityPropertiesToUnset',
    'UpdateIdentityResolutionSettings',
    'UpdateWarehouse',
    'UpdateWarehouseMode',
    'UpdateWorkspace'
);

CREATE TABLE notifications (
    id bigint NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name notification_name NOT NULL,
    payload jsonb NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE metadata (
    key text,
    value text,
    PRIMARY KEY (key)
);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO metadata (key, value) VALUES
    ('encryption_key', encode(gen_random_bytes(64), 'base64')),
    ('installation_id', gen_random_uuid());
