[book]
title = "Meergo Documentation"
language = "en"

[output.html]
additional-css = ["meergo.css"]
git-repository-url = "https://github.com/meergo/meergo/tree/main/doc"

[output.html.fold]
enable = true
level = 0
