// Copyright 2026 Open2b. All rights reserved.
// Use of this source code is governed by an Elastic License 2.0
// that can be found in the LICENSE file.

package state

import (
	"bytes"
	"context"
	"database/sql/driver"
	"fmt"
	"maps"
	"slices"
	"sort"
	"sync"
	"time"

	"github.com/krenalis/krenalis/connectors"
	"github.com/krenalis/krenalis/core/internal/db"
	"github.com/krenalis/krenalis/tools/datacrypt"
	"github.com/krenalis/krenalis/tools/json"
	"github.com/krenalis/krenalis/tools/types"
	"github.com/krenalis/krenalis/warehouses"

	"github.com/google/uuid"
)

// election represents a leader election.
type election struct {
	number   int
	leader   uuid.UUID
	lastSeen time.Time
}

// metadata represents the metadata associated with a Krenalis instance.
type metadata struct {
	// encryptionKey is a slice of random bytes of length 64.
	encryptionKey []byte

	// installationID is an identifier that uniquely identifies a Krenalis
	// installation. It is generated by the PostgreSQL installation script and
	// cannot change over time.
	installationID string
}

// State represents the application state.
type State struct {
	id uuid.UUID
	db *db.DB

	changing           *sync.RWMutex
	connectors         map[string]*Connector
	warehousePlatforms map[string]WarehousePlatform
	metadata           metadata
	sendStats          bool

	mu               *sync.Mutex                 // for the 'pipelines', ..., and 'workspaces' fields
	pipelines        map[int]*Pipeline           // protected by mu
	connections      map[int]*Connection         // protected by mu
	connectionsByKey map[string]*Connection      // protected by mu
	accessKeyByToken map[string]*AccessKey       // protected by mu
	election         election                    // protected by mu
	organizations    map[uuid.UUID]*Organization // protected by mu
	workspaces       map[int]*Workspace          // protected by mu

	notifications struct {
		*notifier
		ch   <-chan notification
		acks sync.Map
	}
	listeners []any
	close     struct {
		ctx    context.Context
		cancel context.CancelFunc
		sync.WaitGroup
	}
}

// OAuthCredentials represents the OAuth client credentials for a connector.
type OAuthCredentials struct {
	ClientID     string
	ClientSecret string
}

// New returns a state given the database, and the OAuth client credentials for
// connectors.
// sendStats indicates whether the state should send statistics or not.
func New(ctx context.Context, db *db.DB, credentials map[string]*OAuthCredentials, sendStats bool) (*State, error) {

	id, err := uuid.NewUUID()
	if err != nil {
		return nil, err
	}

	state := &State{
		id:               id,
		db:               db,
		mu:               new(sync.Mutex),
		changing:         new(sync.RWMutex),
		organizations:    map[uuid.UUID]*Organization{},
		connectors:       map[string]*Connector{},
		workspaces:       map[int]*Workspace{},
		connections:      map[int]*Connection{},
		connectionsByKey: map[string]*Connection{},
		pipelines:        map[int]*Pipeline{},
		sendStats:        sendStats,
	}

	// Init the notifier.
	ch := make(chan notification, 10)
	state.notifications.notifier = newNotifier(db, ch)
	state.notifications.ch = ch

	state.close.ctx, state.close.cancel = context.WithCancel(context.Background())

	// Load the state.
	err = state.load(ctx, credentials)
	if err != nil {
		state.notifications.Close()
		return nil, err
	}

	// Keep the state updated.
	state.close.Add(1)
	go state.keep()

	// Keep elections.
	state.close.Add(1)
	go state.keepElections()

	return state, nil
}

// AccessKeyByToken returns the access key with the provided token.
// The boolean return value reports whether the access key exists.
func (state *State) AccessKeyByToken(token string) (*AccessKey, bool) {
	state.mu.Lock()
	key, ok := state.accessKeyByToken[token]
	state.mu.Unlock()
	return key, ok
}

// Account returns the account with identifier id.
// The boolean return value reports whether the account exists.
func (state *State) Account(id int) (*Account, bool) {
	for _, ws := range state.Workspaces() {
		if a, ok := ws.Account(id); ok {
			return a, true
		}
	}
	return nil, false
}

// Close closes the state. When it is called, no calls to the State methods
// should be in progress, and no further calls should be made.
func (state *State) Close() {
	state.close.cancel()
	state.close.Wait()
	state.notifications.Close()
}

// Connection returns the connection with identifier id.
// The boolean return value reports whether the connection exists.
func (state *State) Connection(id int) (*Connection, bool) {
	state.mu.Lock()
	c, ok := state.connections[id]
	state.mu.Unlock()
	return c, ok
}

// ConnectionByKey returns the connection with the given key.
// The boolean return value reports whether the key exists.
func (state *State) ConnectionByKey(key string) (*Connection, bool) {
	state.mu.Lock()
	c, ok := state.connectionsByKey[key]
	state.mu.Unlock()
	return c, ok
}

// Connections returns all connections.
func (state *State) Connections() []*Connection {
	i := 0
	state.mu.Lock()
	connections := make([]*Connection, len(state.connections))
	for _, c := range state.connections {
		connections[i] = c
		i++
	}
	state.mu.Unlock()
	return connections
}

// Connector returns the connector with the provided code.
// The boolean return value reports whether the connector exists.
func (state *State) Connector(code string) (*Connector, bool) {
	state.mu.Lock()
	c, ok := state.connectors[code]
	state.mu.Unlock()
	return c, ok
}

// Connectors returns all connectors.
func (state *State) Connectors() []*Connector {
	state.mu.Lock()
	connectors := make([]*Connector, len(state.connectors))
	i := 0
	for _, connector := range state.connectors {
		connectors[i] = connector
		i++
	}
	state.mu.Unlock()
	sort.Slice(connectors, func(i, j int) bool {
		return connectors[i].Code < connectors[j].Code
	})
	return connectors
}

// EncryptionKey returns the encryption key. It is 64 bytes long.
func (state *State) EncryptionKey() []byte {
	return state.metadata.encryptionKey
}

// Freeze freezes the state. If the state is updating, the calling goroutine
// blocks until the update and the corresponding calls to the listeners are
// completed. When the state is frozen, no changes are made to the state. For
// each call to Freeze, a call to Unfreeze must be made to unfreeze the state.
func (state *State) Freeze() {
	state.changing.RLock()
}

// ID returns the node identifier.
func (state *State) ID() uuid.UUID {
	return state.id
}

// InstallationID returns the installation ID.
func (state *State) InstallationID() string {
	return state.metadata.installationID
}

// IsLeader reports whether this node is the leader.
func (state *State) IsLeader() bool {
	state.mu.Lock()
	election := state.election
	state.mu.Unlock()
	return election.leader == state.id
}

// NewCipher returns a datacrypt.Cipher bound to the given purpose using the
// state's encryption key.
func (state *State) NewCipher(purpose string) (*datacrypt.Cipher, error) {
	return datacrypt.New(state.metadata.encryptionKey, purpose)
}

// Organization returns the organization with identifier id.
// The boolean return value reports whether the organization exists.
func (state *State) Organization(id uuid.UUID) (*Organization, bool) {
	state.mu.Lock()
	org, ok := state.organizations[id]
	state.mu.Unlock()
	return org, ok
}

// Organizations returns all organizations.
func (state *State) Organizations() []*Organization {
	state.mu.Lock()
	organizations := make([]*Organization, len(state.organizations))
	i := 0
	for _, organization := range state.organizations {
		organizations[i] = organization
		i++
	}
	state.mu.Unlock()
	sort.Slice(organizations, func(i, j int) bool {
		return bytes.Compare(organizations[i].ID[:], organizations[j].ID[:]) < 0
	})
	return organizations
}

// Pipeline returns the pipeline with identifier id.
// The boolean return value reports whether the pipeline exists.
func (state *State) Pipeline(id int) (*Pipeline, bool) {
	state.mu.Lock()
	p, ok := state.pipelines[id]
	state.mu.Unlock()
	return p, ok
}

// Pipelines returns all the pipelines from every connection.
func (state *State) Pipelines() []*Pipeline {
	state.mu.Lock()
	pipelines := make([]*Pipeline, len(state.pipelines))
	i := 0
	for _, pipeline := range state.pipelines {
		pipelines[i] = pipeline
		i++
	}
	state.mu.Unlock()
	sort.Slice(pipelines, func(i, j int) bool {
		return pipelines[i].ID < pipelines[j].ID
	})
	return pipelines
}

// Transaction executes f in a transaction.
func (state *State) Transaction(ctx context.Context, f func(tx *db.Tx) (any, error)) error {
	tx, err := state.db.Begin(ctx)
	if err != nil {
		return err
	}
	var id int64
	var ack chan struct{}
	defer func() {
		if err := recover(); err != nil {
			_ = tx.Rollback(ctx)
			panic(err)
		}
	}()
	n, err := f(tx)
	if err != nil {
		_ = tx.Rollback(ctx)
		return err
	}
	if n == nil {
		return tx.Commit(ctx)
	}
	id, err = state.notifications.Notify(ctx, tx, n)
	if err != nil {
		_ = tx.Rollback(ctx)
		return err
	}
	if id == 0 {
		return tx.Commit(ctx)
	}
	ack = make(chan struct{})
	state.notifications.acks.Store(id, ack)
	defer func() {
		if ack == nil {
			return
		}
		// Attempt to delete the ack channel.
		if _, ok := state.notifications.acks.LoadAndDelete(id); !ok {
			// If the keeper has already removed it, the notification was received.
			// To prevent blocking the keeper, receive from the channel.
			<-ack
		}
	}()
	err = tx.Commit(ctx)
	if err != nil {
		return err
	}
	<-ack
	ack = nil
	return nil
}

// Unfreeze unfreezes the state if there are no more pending Unfreeze calls.
func (state *State) Unfreeze() {
	state.changing.RUnlock()
}

// WarehousePlatform returns the warehouse platform with the provided name.
// The boolean return value reports whether the warehouse platform exists.
func (state *State) WarehousePlatform(name string) (WarehousePlatform, bool) {
	state.mu.Lock()
	platform, ok := state.warehousePlatforms[name]
	state.mu.Unlock()
	return platform, ok
}

// WarehousePlatforms returns all warehouse platforms.
func (state *State) WarehousePlatforms() []WarehousePlatform {
	state.mu.Lock()
	platforms := make([]WarehousePlatform, len(state.warehousePlatforms))
	i := 0
	for _, p := range state.warehousePlatforms {
		platforms[i] = p
		i++
	}
	state.mu.Unlock()
	sort.Slice(platforms, func(i, j int) bool {
		return platforms[i].Name < platforms[j].Name
	})
	return platforms
}

// Workspace returns the workspace with identifier id.
// The boolean return value reports whether the workspace exists.
func (state *State) Workspace(id int) (*Workspace, bool) {
	state.mu.Lock()
	ws, ok := state.workspaces[id]
	state.mu.Unlock()
	return ws, ok
}

// Workspaces returns all the workspaces.
func (state *State) Workspaces() []*Workspace {
	i := 0
	state.mu.Lock()
	workspaces := make([]*Workspace, len(state.workspaces))
	for _, ws := range state.workspaces {
		workspaces[i] = ws
		i++
	}
	state.mu.Unlock()
	return workspaces
}

// AccessKeyType represents an access key type.
type AccessKeyType int

const (
	AccessKeyTypeAPI AccessKeyType = iota
	AccessKeyTypeMCP
)

// Scan implements the sql.Scanner interface.
func (typ *AccessKeyType) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an AccessKeyType value", src)
	}
	var t AccessKeyType
	switch s {
	case "API":
		t = AccessKeyTypeAPI
	case "MCP":
		t = AccessKeyTypeMCP
	default:
		return fmt.Errorf("invalid AccessKeyType: %s", s)
	}
	*typ = t
	return nil
}

// String returns the string representation of typ.
// It panics if typ is not a valid AccessKeyType value.
func (typ AccessKeyType) String() string {
	m, err := typ.Value()
	if err != nil {
		panic("invalid access key type")
	}
	return m.(string)
}

// Value implements driver.Valuer interface.
// It returns an error if typ is not a valid AccessKeyType.
func (typ AccessKeyType) Value() (driver.Value, error) {
	switch typ {
	case AccessKeyTypeAPI:
		return "API", nil
	case AccessKeyTypeMCP:
		return "MCP", nil
	}
	return nil, fmt.Errorf("not a valid AccessKeyType: %d", typ)
}

// AccessKey represents an access key.
type AccessKey struct {
	ID           int
	Organization uuid.UUID
	Workspace    int
	Type         AccessKeyType
}

// Organization represents an organization.
type Organization struct {
	mu         *sync.Mutex
	workspaces map[int]*Workspace
	members    map[int]struct{}
	ID         uuid.UUID
	Name       string
}

// HasMember reports whether the organization has a member with the given ID.
func (organization *Organization) HasMember(id int) bool {
	organization.mu.Lock()
	_, ok := organization.members[id]
	organization.mu.Unlock()
	return ok
}

// Workspace returns the workspace of the organization with identifier id.
// The boolean return value reports whether the workspace exists.
func (organization *Organization) Workspace(id int) (*Workspace, bool) {
	organization.mu.Lock()
	w, ok := organization.workspaces[id]
	organization.mu.Unlock()
	return w, ok
}

// Workspaces returns all the workspaces of the organization.
func (organization *Organization) Workspaces() []*Workspace {
	organization.mu.Lock()
	workspaces := make([]*Workspace, len(organization.workspaces))
	i := 0
	for _, w := range organization.workspaces {
		workspaces[i] = w
		i++
	}
	organization.mu.Unlock()
	return workspaces
}

// WarehousePlatform represents a warehouse platform.
type WarehousePlatform struct {
	Name string
}

// WarehouseMode represents a data warehouse mode.
type WarehouseMode int

const (
	Normal WarehouseMode = iota
	Inspection
	Maintenance
)

// Scan implements the sql.Scanner interface.
func (mode *WarehouseMode) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an WarehouseMode value", src)
	}
	var m WarehouseMode
	switch s {
	case "Normal":
		m = Normal
	case "Inspection":
		m = Inspection
	case "Maintenance":
		m = Maintenance
	default:
		return fmt.Errorf("invalid WarehouseMode: %s", s)
	}
	*mode = m
	return nil
}

// String returns the string representation of mode.
// It panics if mode is not a valid WarehouseMode value.
func (mode WarehouseMode) String() string {
	m, err := mode.Value()
	if err != nil {
		panic("invalid warehouse mode")
	}
	return m.(string)
}

// Value implements driver.Valuer interface.
// It returns an error if typ is not a valid WarehouseMode.
func (mode WarehouseMode) Value() (driver.Value, error) {
	switch mode {
	case Normal:
		return "Normal", nil
	case Inspection:
		return "Inspection", nil
	case Maintenance:
		return "Maintenance", nil
	}
	return nil, fmt.Errorf("not a valid WarehouseMode: %d", mode)
}

// Workspace represents a workspace.
type Workspace struct {
	mu        *sync.Mutex
	Warehouse struct {
		Platform    string
		Mode        WarehouseMode
		Settings    json.Value
		MCPSettings json.Value // it can be a JSON object or json.Value(nil)
	}
	connections                    map[int]*Connection
	runs                           map[int]*PipelineRun // pipeline runs in progress.
	ID                             int
	organization                   *Organization
	Name                           string
	ProfileSchema                  types.Type // without meta properties.
	PrimarySources                 map[string]int
	accounts                       map[int]*Account
	ResolveIdentitiesOnBatchImport bool
	Identifiers                    []string
	UIPreferences                  UIPreferences
	IR                             struct {
		ID        *string    // nil means no IR in execution.
		StartTime *time.Time // nil means IR was never started.
		EndTime   *time.Time // nil means IR is running or has never started.
	}
	AlterProfileSchema struct {
		ID             *string    // nil means no profile schema alterations in execution.
		StartTime      *time.Time // nil means profile schema alteration was never started.
		EndTime        *time.Time // nil means profile schema alteration is running or has never started.
		Err            *string    // pointer to empty string if no errors occurred during last execution of alter profile schema.
		Schema         types.Type
		PrimarySources map[string]int // nil if, and only if, schema alteration is not in execution.
		Operations     []warehouses.AlterOperation
	}
	pipelinesToPurge []int // never nil
}

// Account returns the account with identifier id. The boolean return value
// reports whether the account exists.
func (workspace *Workspace) Account(id int) (*Account, bool) {
	workspace.mu.Lock()
	a, ok := workspace.accounts[id]
	workspace.mu.Unlock()
	return a, ok
}

// AccountByCode returns the account with the given code for the specified
// connector. The boolean indicates whether the account exists.
func (workspace *Workspace) AccountByCode(connector, code string) (*Account, bool) {
	var a *Account
	workspace.mu.Lock()
	for _, account := range workspace.accounts {
		if account.connector.Code == connector && account.Code == code {
			a = account
			break
		}
	}
	workspace.mu.Unlock()
	return a, a != nil
}

// Connection returns the connection of the workspace with identifier id.
// The boolean return value reports whether the connection exists.
func (workspace *Workspace) Connection(id int) (*Connection, bool) {
	workspace.mu.Lock()
	c, ok := workspace.connections[id]
	workspace.mu.Unlock()
	return c, ok
}

// Connections returns all the connections of the workspace.
func (workspace *Workspace) Connections() []*Connection {
	workspace.mu.Lock()
	connections := make([]*Connection, len(workspace.connections))
	i := 0
	for _, c := range workspace.connections {
		connections[i] = c
		i++
	}
	workspace.mu.Unlock()
	return connections
}

// Run returns the pipeline run in the workspace with the given id.
// The boolean return value indicates whether the run exists.
func (workspace *Workspace) Run(id int) (*PipelineRun, bool) {
	workspace.mu.Lock()
	exe, ok := workspace.runs[id]
	workspace.mu.Unlock()
	return exe, ok
}

// NumPipelinesToPurge returns the number of pipelines to purge for the
// workspace.
func (workspace *Workspace) NumPipelinesToPurge() int {
	workspace.mu.Lock()
	n := len(workspace.pipelinesToPurge)
	workspace.mu.Unlock()
	return n
}

// Organization returns the organization of the workspace.
func (workspace *Workspace) Organization() *Organization {
	workspace.mu.Lock()
	organization := workspace.organization
	workspace.mu.Unlock()
	return organization
}

// PipelinesToPurge returns the identifiers of pipelines that require purging,
// specifically those that have been deleted but still have user identifiers or
// destination users to be purged from the data warehouse. It never returns nil.
func (workspace *Workspace) PipelinesToPurge() []int {
	workspace.mu.Lock()
	pipelines := workspace.pipelinesToPurge
	workspace.mu.Unlock()
	return slices.Clone(pipelines)
}

// UIPreferences represents the UI preferences of a workspace.
type UIPreferences struct {
	Profile struct {
		Image     string // property path.
		FirstName string // property path.
		LastName  string // property path.
		Extra     string // property path.
	}
}

// TimeLayouts represents the layouts used to format datetime, date, and time
// values.
type TimeLayouts struct {
	DateTime string
	Date     string
	Time     string
}

// Connector represents a connector.
type Connector struct {
	Code                   string
	Label                  string
	Type                   ConnectorType
	Categories             connectors.Categories
	SourceTargets          ConnectorTargets
	DestinationTargets     ConnectorTargets
	Terms                  ConnectorTerms
	SendingMode            *SendingMode
	HasSheets              bool
	HasSourceSettings      bool
	HasDestinationSettings bool
	TimeLayouts            TimeLayouts
	FileExtension          string
	SampleQuery            string
	WebhooksPer            WebhooksPer
	OAuth                  *OAuth
	EndpointGroups         []connectors.EndpointGroup
	Strategies             bool
	FallbackToRequestIP    bool
	Documentation          connectors.Documentation
}

// ConnectorTargets represents the targets of a connector.
type ConnectorTargets int

const (
	EventsFlag ConnectorTargets = 1 << iota
	UsersFlag
	GroupsFlag
)

// Contains reports whether t contains the given target.
func (t ConnectorTargets) Contains(target Target) bool {
	switch target {
	case TargetEvent:
		return t&EventsFlag != 0
	case TargetUser:
		return t&UsersFlag != 0
	case TargetGroup:
		return t&GroupsFlag != 0
	}
	panic("invalid target")
}

// ConnectorTerms represents the terms that a connector uses to refer to various
// entities, such as users or groups.
type ConnectorTerms struct {
	User   string
	Users  string
	UserID string
	// Group  string  TODO(Marco): implement groups
	// Groups string
}

// ConnectorType represents a connector type.
type ConnectorType int

const (
	Application ConnectorType = iota + 1
	Database
	File
	FileStorage
	MessageBroker
	SDK
	Webhook
)

// Scan implements the sql.Scanner interface.
func (typ *ConnectorType) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.ConnectorType value", src)
	}
	var t ConnectorType
	switch s {
	case "Application":
		t = Application
	case "Database":
		t = Database
	case "File":
		t = File
	case "FileStorage":
		t = FileStorage
	case "MessageBroker":
		t = MessageBroker
	case "SDK":
		t = SDK
	case "Webhook":
		t = Webhook
	default:
		return fmt.Errorf("invalid state.ConnectionType: %s", s)
	}
	*typ = t
	return nil
}

// String returns the string representation of typ.
// It panics if typ is not a valid ConnectorType value.
func (typ ConnectorType) String() string {
	s, err := typ.Value()
	if err != nil {
		panic("invalid connector type")
	}
	return s.(string)
}

// Value implements driver.Valuer interface.
// It returns an error if typ is not a valid ConnectorType.
func (typ ConnectorType) Value() (driver.Value, error) {
	switch typ {
	case Application:
		return "Application", nil
	case Database:
		return "Database", nil
	case File:
		return "File", nil
	case FileStorage:
		return "FileStorage", nil
	case MessageBroker:
		return "MessageBroker", nil
	case SDK:
		return "SDK", nil
	case Webhook:
		return "Webhook", nil
	}
	return nil, fmt.Errorf("not a valid ConnectorType: %d", typ)
}

type WebhooksPer int

const (
	WebhooksPerNone WebhooksPer = iota
	WebhooksPerAccount
	WebhooksPerConnection
	WebhooksPerConnector
)

// Scan implements the sql.Scanner interface.
func (per *WebhooksPer) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.WebhooksPer value", src)
	}
	var p WebhooksPer
	switch s {
	case "None":
		p = WebhooksPerNone
	case "Account":
		p = WebhooksPerAccount
	case "Connection":
		p = WebhooksPerConnection
	case "Connector":
		p = WebhooksPerConnector
	default:
		return fmt.Errorf("invalid state.WebhooksPer: %s", s)
	}
	*per = p
	return nil
}

// String returns the string representation of w.
// It panics if w is not a valid WebhooksPer value.
func (per WebhooksPer) String() string {
	s, err := per.Value()
	if err != nil {
		panic("invalid webhooksPer value")
	}
	return s.(string)
}

// Value implements driver.Valuer interface.
// It returns an error if typ is not a valid Role.
func (per WebhooksPer) Value() (driver.Value, error) {
	switch per {
	case WebhooksPerNone:
		return "None", nil
	case WebhooksPerAccount:
		return "Account", nil
	case WebhooksPerConnection:
		return "Connection", nil
	case WebhooksPerConnector:
		return "Connector", nil
	}
	return nil, fmt.Errorf("not a valid WebhooksPer: %d", per)
}

// An OAuth represents OAuth data required to authenticate with a connector.
type OAuth struct {
	connectors.OAuth
	ClientID     string
	ClientSecret string
}

// Account represents an account.
type Account struct {
	mu           *sync.Mutex
	ID           int
	workspace    *Workspace
	connector    *Connector
	Code         string
	AccessToken  string
	RefreshToken string
	ExpiresIn    time.Time
}

// Workspace returns the workspace of the account.
func (account *Account) Workspace() *Workspace {
	account.mu.Lock()
	w := account.workspace
	account.mu.Unlock()
	return w
}

// Connector returns the connector of the account.
func (account *Account) Connector() *Connector {
	account.mu.Lock()
	c := account.connector
	account.mu.Unlock()
	return c
}

// Strategy represents a strategy.
// Can be "Conversion", "Fusion", "Isolation", and "Preservation".
type Strategy string

// Connection represents a connection.
type Connection struct {
	mu                *sync.Mutex
	organization      *Organization
	workspace         *Workspace
	ID                int
	Name              string
	connector         *Connector
	Role              Role
	account           *Account
	Strategy          *Strategy
	SendingMode       *SendingMode
	LinkedConnections []int // Non-nil if events are supported; otherwise nil.
	Keys              []string
	Settings          json.Value
	UsersQuery        string
	pipelines         map[int]*Pipeline
	Health            Health
}

// Account returns the account of the connection. The boolean return value
// reports whether the connection has an account.
func (connection *Connection) Account() (*Account, bool) {
	connection.mu.Lock()
	a := connection.account
	connection.mu.Unlock()
	return a, a != nil
}

// Connector returns the connector of the connection.
func (connection *Connection) Connector() *Connector {
	connection.mu.Lock()
	c := connection.connector
	connection.mu.Unlock()
	return c
}

// Organization returns the organization of the connection.
func (connection *Connection) Organization() *Organization {
	connection.mu.Lock()
	o := connection.organization
	connection.mu.Unlock()
	return o
}

// Pipeline returns the pipeline of the connection with identifier id.
// The boolean return value reports whether the pipeline exists.
func (connection *Connection) Pipeline(id int) (*Pipeline, bool) {
	connection.mu.Lock()
	p, ok := connection.pipelines[id]
	connection.mu.Unlock()
	return p, ok
}

// Pipelines returns the pipelines of the connection.
func (connection *Connection) Pipelines() []*Pipeline {
	connection.mu.Lock()
	pipelines := make([]*Pipeline, len(connection.pipelines))
	i := 0
	for _, p := range connection.pipelines {
		pipelines[i] = p
		i++
	}
	connection.mu.Unlock()
	sort.Slice(pipelines, func(i, j int) bool {
		return pipelines[i].ID < pipelines[j].ID
	})
	return pipelines
}

// Workspace returns the workspace of the connection.
func (connection *Connection) Workspace() *Workspace {
	connection.mu.Lock()
	w := connection.workspace
	connection.mu.Unlock()
	return w
}

// Health is an indicator of the current state of a pipeline or a connection.
type Health int

const (
	Healthy Health = iota
	NoRecentData
	RecentError
)

// Scan implements the sql.Scanner interface.
func (health *Health) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Health value", src)
	}
	var h Health
	switch s {
	case "Healthy":
		h = Healthy
	case "NoRecentData":
		h = NoRecentData
	case "RecentError":
		h = RecentError
	default:
		return fmt.Errorf("invalid state.Health: %s", s)
	}
	*health = h
	return nil
}

// String returns the string representation of health.
// It panics if health is not a valid Health value.
func (health Health) String() string {
	switch health {
	case Healthy:
		return "Healthy"
	case NoRecentData:
		return "NoRecentData"
	case RecentError:
		return "RecentError"
	}
	panic("invalid connection health")
}

// Value implements driver.Valuer interface.
// It returns an error if health is not a valid Health.
func (health Health) Value() (driver.Value, error) {
	switch health {
	case Healthy:
		return "Healthy", nil
	case NoRecentData:
		return "NoRecentData", nil
	case RecentError:
		return "RecentError", nil
	}
	return nil, fmt.Errorf("not a valid Health: %d", health)
}

// Role represents a role.
type Role int

const (
	Both        Role = iota // both
	Source                  // source
	Destination             // destination
)

// Scan implements the sql.Scanner interface.
func (role *Role) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Role value", src)
	}
	var r Role
	switch s {
	case "Both":
		r = Both
	case "Source":
		r = Source
	case "Destination":
		r = Destination
	default:
		return fmt.Errorf("invalid state.Role: %s", s)
	}
	*role = r
	return nil
}

// String returns the string representation of role.
// It panics if role is not a valid Role value.
func (role Role) String() string {
	switch role {
	case Source:
		return "Source"
	case Destination:
		return "Destination"
	}
	panic("invalid connection role")
}

// Value implements driver.Valuer interface.
// It returns an error if role is not a valid Role.
func (role Role) Value() (driver.Value, error) {
	switch role {
	case Source:
		return "Source", nil
	case Destination:
		return "Destination", nil
	}
	return nil, fmt.Errorf("not a valid Role: %d", role)
}

// SendingMode represents a sending mode.
type SendingMode string

const (
	Client          SendingMode = "Client"
	Server          SendingMode = "Server"
	ClientAndServer SendingMode = "ClientAndServer"
)

func (sm SendingMode) Contains(mode SendingMode) bool {
	return sm == ClientAndServer || sm == mode
}

// Compression represents the compression of a file connection.
type Compression string

const (
	NoCompression     Compression = ""
	ZipCompression    Compression = "Zip"
	GzipCompression   Compression = "Gzip"
	SnappyCompression Compression = "Snappy"
)

// ContentType returns the content type to use for a file compressed with
// compression c. It returns an empty string if c is NoCompression.
func (c Compression) ContentType() string {
	switch c {
	case NoCompression:
		return ""
	case ZipCompression:
		return "application/zip"
	case GzipCompression:
		return "application/gzip"
	case SnappyCompression:
		return "application/x-snappy-framed"
	}
	panic(fmt.Sprintf("invalid state.Compression: %s", c))
}

// Ext returns the file extension to use when the file is compressed with
// compression c. It returns an empty string if c is NoCompression.
func (c Compression) Ext() string {
	switch c {
	case NoCompression:
		return ""
	case ZipCompression:
		return ".zip"
	case GzipCompression:
		return ".gz"
	case SnappyCompression:
		return ".sz"
	}
	panic(fmt.Sprintf("invalid state.Compression: %s", c))
}

// Target represents a target.
type Target int

const (
	TargetEvent Target = iota + 1
	TargetUser
	TargetGroup
)

// Scan implements the sql.Scanner interface.
func (target *Target) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Target value", src)
	}
	switch s {
	case "Event":
		*target = TargetEvent
	case "User":
		*target = TargetUser
	case "Group":
		*target = TargetGroup
	default:
		return fmt.Errorf("invalid state.Target: %s", s)
	}
	return nil
}

// String returns the string representation of target.
// It panics if target is not a valid Target value.
func (target Target) String() string {
	switch target {
	case TargetEvent:
		return "Event"
	case TargetUser:
		return "User"
	case TargetGroup:
		return "Group"
	}
	panic("invalid target")
}

// Value implements driver.Valuer interface.
// It returns an error if target is not a valid Target.
func (target Target) Value() (driver.Value, error) {
	switch target {
	case TargetEvent:
		return "Event", nil
	case TargetUser:
		return "User", nil
	case TargetGroup:
		return "Group", nil
	}
	return nil, fmt.Errorf("not a valid Target: %d", target)
}

type Pipeline struct {
	mu                 *sync.Mutex
	ID                 int
	connection         *Connection
	format             *Connector
	run                *PipelineRun
	propertiesToUnset  []string // is not nil only for source pipelines on users.
	Target             Target
	Name               string
	Enabled            bool
	EventType          string
	ScheduleStart      int16
	SchedulePeriod     int16
	InSchema           types.Type
	OutSchema          types.Type
	Filter             *Where
	Transformation     Transformation
	Query              string
	Path               string
	Sheet              string
	Compression        Compression
	OrderBy            string
	FormatSettings     json.Value
	ExportMode         ExportMode
	Matching           Matching
	UpdateOnDuplicates bool
	TableName          string
	TableKey           string
	UserIDColumn       string
	UpdatedAtColumn    string
	UpdatedAtFormat    string
	Reload             bool
	Incremental        bool
	Health             Health
}

// Connection returns the connection of the pipeline.
func (pipeline *Pipeline) Connection() *Connection {
	pipeline.mu.Lock()
	c := pipeline.connection
	pipeline.mu.Unlock()
	return c
}

// Run returns the current run of the pipeline.
// The boolean return value indicates whether the pipeline is currently running.
func (pipeline *Pipeline) Run() (*PipelineRun, bool) {
	pipeline.mu.Lock()
	ex := pipeline.run
	pipeline.mu.Unlock()
	return ex, ex != nil
}

// PropertiesToUnset returns the identity properties of the pipeline that should
// be unset. It is non-nil for source pipelines on users.
func (pipeline *Pipeline) PropertiesToUnset() []string {
	pipeline.mu.Lock()
	c := pipeline.propertiesToUnset
	pipeline.mu.Unlock()
	return c
}

// Format returns the format connector of the pipeline.
func (pipeline *Pipeline) Format() *Connector {
	pipeline.mu.Lock()
	c := pipeline.format
	pipeline.mu.Unlock()
	return c
}

// PipelineRun represents a pipeline run.
type PipelineRun struct {
	mu          *sync.Mutex
	ID          int
	node        *uuid.UUID
	pipeline    *Pipeline
	Incremental bool
	Cursor      time.Time
	StartTime   time.Time
}

// Pipeline returns the pipeline associated with the run.
func (ex *PipelineRun) Pipeline() *Pipeline {
	ex.mu.Lock()
	p := ex.pipeline
	ex.mu.Unlock()
	return p
}

// Node returns the node on which the run is currently executing.
// The boolean return value indicates whether the run is assigned to a node.
func (ex *PipelineRun) Node() (uuid.UUID, bool) {
	ex.mu.Lock()
	node := ex.node
	ex.mu.Unlock()
	if node == nil {
		return uuid.UUID{}, false
	}
	return *node, true
}

type Matching struct {
	In  string // property path.
	Out string // property path.
}

// Language represents a transformation language.
type Language int

const (
	JavaScript Language = iota
	Python
)

// Scan implements the sql.Scanner interface.
func (lang *Language) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot scan a %T value into an state.Language value", src)
	}
	switch s {
	case "JavaScript":
		*lang = JavaScript
	case "Python":
		*lang = Python
	default:
		return fmt.Errorf("invalid state.Language: %s", s)
	}
	return nil
}

func (lang Language) String() string {
	switch lang {
	case JavaScript:
		return "JavaScript"
	case Python:
		return "Python"
	}
	panic("invalid language")
}

// Transformation represents a transformation.
type Transformation struct {
	Mapping  map[string]string
	Function *TransformationFunction
	InPaths  []string // sorted alphabetically.
	OutPaths []string // sorted alphabetically.
}

// Equal reports whether t and t2 represent the same transformation.
// Both t and t2 must be well-formed transformations.
func (t Transformation) Equal(t2 Transformation) bool {
	if t.Function == nil || t2.Function == nil {
		if !maps.Equal(t.Mapping, t2.Mapping) {
			return false
		}
	} else {
		if *t.Function != *t2.Function {
			return false
		}
		if !slices.Equal(t.InPaths, t2.InPaths) || !slices.Equal(t.OutPaths, t2.OutPaths) {
			return false
		}
	}
	return true
}

// TransformationFunction represents a transformation function.
type TransformationFunction struct {
	ID           string
	Version      string
	Language     Language
	Source       string
	PreserveJSON bool
}

// ExportMode represents one of the three export modes.
type ExportMode string

const (
	CreateOnly     ExportMode = "CreateOnly"
	UpdateOnly     ExportMode = "UpdateOnly"
	CreateOrUpdate ExportMode = "CreateOrUpdate"
)
