-- Keep in sync with the events.eventsMergeTable variable.

CREATE TABLE events
(
    `user` UUID,
    `anonymousId` String,
    `category` String,
    `context_app_name` String,
    `context_app_version` String,
    `context_app_build` String,
    `context_app_namespace` String,
    `context_browser_name` Enum8('Chrome' = 1, 'Safari' = 2, 'Edge' = 3, 'Firefox' = 4, 'Samsung Internet' = 5, 'Opera' = 6, 'Other' = 7),
    `context_browser_other` String,
    `context_browser_version` String,
    `context_campaign_name` String,
    `context_campaign_source` String,
    `context_campaign_medium` String,
    `context_campaign_term` String,
    `context_campaign_content` String,
    `context_device_id` String,
    `context_device_advertisingId` String,
    `context_device_adTrackingEnabled` Bool,
    `context_device_manufacturer` String,
    `context_device_model` String,
    `context_device_name` String,
    `context_device_type` String,
    `context_device_token` String,
    `context_ip` IPv6,
    `context_library_name` String,
    `context_library_version` String,
    `context_locale` String,
    `context_location_city` String,
    `context_location_country` String,
    `context_location_latitude` Float64,
    `context_location_longitude` Float64,
    `context_location_speed` Float64,
    `context_network_bluetooth` Bool,
    `context_network_carrier` String,
    `context_network_cellular` Bool,
    `context_network_wifi` Bool,
    `context_os_name` Enum8('Android' = 1, 'Windows' = 2, 'iOS' = 3, 'macOS' = 4, 'Linux' = 5, 'Chrome OS' = 6, 'Other' = 7),
    `context_os_version` String,
    `context_page_path` String,
    `context_page_referrer` String,
    `context_page_search` String,
    `context_page_title` String,
    `context_page_url` String,
    `context_referrer_id` String,
    `context_referrer_type` String,
    `context_screen_width` Int16,
    `context_screen_height` Int16,
    `context_screen_density` Decimal(3,2),
    `context_session_id` Int64,
    `context_session_start` Bool,
    `context_timezone` String,
    `context_userAgent` String,
    `event` String,
    `groupId` String,
    `messageId` String,
    `name` String,
    `properties` String,
    `receivedAt` DateTime,
    `sentAt` DateTime,
    `source` Int32,
    `timestamp` DateTime,
    `traits` String,
    `type` Enum8('alias' = 1, 'identify' = 2, 'group' = 3, 'page' = 4, 'screen' = 5, 'track' = 6),
    `userId` String
)
ENGINE = MergeTree
PRIMARY KEY (source, date, user_id, timestamp)
ORDER BY (source, date, user_id, timestamp)
SETTINGS index_granularity = 8192;
