{
 "title": "Go metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Heap Alloc vs RAM Totale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app=\"meergo\"}",
     "legendFormat": "Go Alloc Heap"
    },
    { "expr": "process_resident_memory_bytes", "legendFormat": "Process RAM Totale" }
   ]
  },
  {
   "title": "Heap / Stack Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"meergo\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"meergo\"}",
     "legendFormat": "Heap idle"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"meergo\"}",
     "legendFormat": "Stack in-use"
    }
   ]
  },
  {
   "title": "GC Duration & Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{app=\"meergo\"}[1m])",
     "legendFormat": "GC Duration Rate (s/sec)"
    },
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"meergo\"}[1m])",
     "legendFormat": "GC Count Rate (/sec)"
    },
    {
     "expr": "histogram_quantile(0.95, rate(go_gc_duration_seconds_bucket{job=\"meergo\"}[5m]))",
     "legendFormat": "GC 95th percentile (s)"
    }
   ]
  },
  {
   "title": "Goroutine Attive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"meergo\"}",
     "legendFormat": "goroutines"
    }
   ]
  }
 ]
}