DO $$
    BEGIN
    IF NOT EXISTS (SELECT FROM pg_type WHERE typname = '_operation') THEN
        CREATE TYPE _operation AS ENUM ('IdentityResolution', 'AlterUserColumns');
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS _operations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    operation _operation NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    users_version integer,
    PRIMARY KEY ("id")
);