name: Run go run ./test/commit

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main

permissions: {}

jobs:
  tests:
    # Note that 'ubuntu-latest' includes the Docker server, which is required to
    # run './test/commit'.
    runs-on: ubuntu-latest

    timeout-minutes: 40

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-go@v5
        with:
          # Keep in sync with the version within ".github/workflows/send-sourcemaps-to-sentry.yml".
          # Keep in sync with the version within "Dockerfile".
          # Keep in sync with the version within "go.mod".
          go-version: "1.26"

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          pip install pandas
          pip install pyarrow

      - env:
          KRENALIS_TEST_GOOGLE_ANALYTICS_API_SECRET: ${{ secrets.KRENALIS_TEST_GOOGLE_ANALYTICS_API_SECRET }}
          KRENALIS_TEST_GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.KRENALIS_TEST_GOOGLE_ANALYTICS_MEASUREMENT_ID }}
          KRENALIS_TEST_GOOGLE_ANALYTICS_COLLECTION_ENDPOINT: ${{ secrets.KRENALIS_TEST_GOOGLE_ANALYTICS_COLLECTION_ENDPOINT }}
          KRENALIS_TEST_KLAVIYO_PRIVATE_API_KEY: ${{ secrets.KRENALIS_TEST_KLAVIYO_PRIVATE_API_KEY }}
          KRENALIS_TEST_MIXPANEL_PROJECT_ID: ${{ secrets.KRENALIS_TEST_MIXPANEL_PROJECT_ID }}
          KRENALIS_TEST_MIXPANEL_PROJECT_TOKEN: ${{ secrets.KRENALIS_TEST_MIXPANEL_PROJECT_TOKEN }}
          KRENALIS_TEST_MIXPANEL_DATA_RESIDENCY: ${{ secrets.KRENALIS_TEST_MIXPANEL_DATA_RESIDENCY }}
          KRENALIS_TEST_POSTHOG_API_KEY: ${{ secrets.KRENALIS_TEST_POSTHOG_API_KEY }}
          KRENALIS_TEST_POSTHOG_PROJECT_REGION: ${{ secrets.KRENALIS_TEST_POSTHOG_PROJECT_REGION }}
        run: go run ./test/commit -no-go-test

      - name: Check that the repository is clean
        run: ./test/commit/repo_is_clean.bash
