on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          # Keep in sync with the version within "Dockerfile".
          # Keep in sync with the version within "go.mod".
          # Keep in sync with the version within "go.work".
          go-version: "1.23"

      - uses: denoland/setup-deno@v2
        with:
          # Keep in sync with the version within "commit/commit.go".
          deno-version: v2.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: go run ./commit
        run: go run ./commit

      - uses: numtide/clean-git-action@v2
