name: Send sourcemaps to Sentry

on:
  workflow_dispatch:
  push:
    # Only run the action when a file is modified that could, at least
    # theoretically, affect the files whose Debug IDs are sent to Sentry.
    #
    # Among these, in addition to the Admin assets, it is necessary to include
    # the go.mod (since it contains the esbuild version) and the GitHub Action
    # file descriptions, among which there is the build and push to Sentry
    # process.
    paths:
      - "go.mod"
      - "assets/**"
      - ".github/workflows/**"

jobs:
  upload-sourcemaps-to-sentry:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go (needed for building assets)
        uses: actions/setup-go@v5
        with:
          # Keep in sync with the version within ".github/workflows/go-run-commit.yml".
          # Keep in sync with the version within "Dockerfile".
          # Keep in sync with the version within "go.mod".
          go-version: "1.25"

      - name: Install Brotli (for decompressing built assets)
        run: sudo apt install -y brotli

      - name: Install the Sentry CLI tool
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Build assets running 'go generate'
        run: go generate
        working-directory: ./cmd/meergo

      - name: Decompress .br assets using Brotli
        run: find -name "*.br" -not -path "./shoelace/*" | xargs brotli -dvf
        working-directory: ./cmd/meergo/meergo-assets

      - name: Upload the source maps to Sentry
        run: sentry-cli sourcemaps upload .
        env:
          # These secrets can be configured at:
          # https://github.com/meergo/meergo/settings/secrets/actions.
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        working-directory: ./cmd/meergo/meergo-assets
